const LOCAL_STOCKS = [
    {t:'.NS',n:'Nse India'},
    {t:'20MICRONS.NS',n:'20 Microns'},
    {t:'21STCENMGM.NS',n:'21St Century Management Services'},
    {t:'360ONE.NS',n:'360 One Wam'},
    {t:'3BBLACKBIO.NS',n:'3B Blackbio Dx'},
    {t:'3IINFOLTD.NS',n:'3I Infotech'},
    {t:'3MINDIA.NS',n:'3M India'},
    {t:'3PLAND.NS',n:'3P Land Holdings'},
    {t:'5PAISA.NS',n:'5Paisa Capital'},
    {t:'63MOONS.NS',n:'63 Moons Technologies'},
    {t:'A2ZINFRA.NS',n:'A2Z Infra Engineering'},
    {t:'AAATECH.NS',n:'Aaa Technologies'},
    {t:'AADHARHFC.NS',n:'Aadhar Housing Finance'},
    {t:'AARNAV.NS',n:'Aarnav Fashions'},
    {t:'AARON.NS',n:'Aaron Industries'},
    {t:'AARTECH.NS',n:'Aartech Solonics'},
    {t:'AARTIDRUGS.NS',n:'Aarti Drugs'},
    {t:'AARTIIND.NS',n:'Aarti'},
    {t:'AARTIPHARM.NS',n:'Aarti Pharmalabs'},
    {t:'AARTISURF.NS',n:'Aarti Surfactants'},
    {t:'AARVI.NS',n:'Aarvi Encon'},
    {t:'AAVAS.NS',n:'Aavas Financiers'},
    {t:'ABB.NS',n:'Abb'},
    {t:'ABBOTINDIA.NS',n:'Abbott India'},
    {t:'ABCAPITAL.NS',n:'Aditya Birla Capital'},
    {t:'ABCOTS.NS',n:'A B Cotspin India'},
    {t:'ABDL.NS',n:'Allied Blenders And Distillers'},
    {t:'ABFRL.NS',n:'Aditya Birla Fashion And Retail'},
    {t:'ABINFRA.NS',n:'A B Infrabuild'},
    {t:'ABLBL.NS',n:'Aditya Birla Lifestyle Brands'},
    {t:'ABMINTLLTD.NS',n:'Abm International'},
    {t:'ABMKNO.NS',n:'Abm Knowledgeware'},
    {t:'ABREL.NS',n:'Aditya Birla Real Estate'},
    {t:'ABSLAMC.NS',n:'Aditya Birla Sun Life Amc'},
    {t:'ACC.NS',n:'Acc'},
    {t:'ACCELYA.NS',n:'Accelya Solutions India'},
    {t:'ACCURACY.NS',n:'Accuracy Shipping'},
    {t:'ACE.NS',n:'Action Construction Equipment'},
    {t:'ACEINTEG.NS',n:'Ace Integrated Solutions'},
    {t:'ACI.NS',n:'Archean Chemical Industries'},
    {t:'ACL.NS',n:'Andhra Cements'},
    {t:'ACMESOLAR.NS',n:'Acme Solar Holdings'},
    {t:'ACSTECH.NS',n:'Acs Technologies'},
    {t:'ACUTAAS.NS',n:'Acutaas Chemicals'},
    {t:'ADANIENSOL.NS',n:'Adani Energy Solutions'},
    {t:'ADANIENT.NS',n:'Adani'},
    {t:'ADANIGREEN.NS',n:'Adani Green'},
    {t:'ADANIPORTS.NS',n:'Adani Ports'},
    {t:'ADANIPOWER.NS',n:'Adani Power'},
    {t:'ADANITOTAL.NS',n:'Adani Total'},
    {t:'ADFFOODS.NS',n:'Adf Foods'},
    {t:'ADL.NS',n:'Archidply Decor'},
    {t:'ADOR.NS',n:'Ador Welding'},
    {t:'ADROITINFO.NS',n:'Adroit Infotech'},
    {t:'ADSL.NS',n:'Allied Digital Services'},
    {t:'ADVAIT.NS',n:'Advait Energy Transitions'},
    {t:'ADVANCE.NS',n:'Advance Agrolife'},
    {t:'ADVANIHOTR.NS',n:'Advani Hotels & Resorts (India)'},
    {t:'ADVENTHTL.NS',n:'Advent Hotels International'},
    {t:'ADVENZYMES.NS',n:'Advanced Enzyme Technologies'},
    {t:'AEGISLOG.NS',n:'Aegis Logistics'},
    {t:'AEGISVOPAK.NS',n:'Aegis Vopak Terminals'},
    {t:'AEPL.NS',n:'Artemis Electricals And Projects'},
    {t:'AEQUS.NS',n:'Aequs'},
    {t:'AEROENTER.NS',n:'Aeroflex Enterprises'},
    {t:'AEROFLEX.NS',n:'Aeroflex Industries'},
    {t:'AERONEU.NS',n:'Aeroflex Neu'},
    {t:'AETHER.NS',n:'Aether Industries'},
    {t:'AFCONS.NS',n:'Afcons Infrastructure'},
    {t:'AFFLE.NS',n:'Affle 3I'},
    {t:'AFSL.NS',n:'Abans Financial Services'},
    {t:'AGARIND.NS',n:'Agarwal Industrial Corporation'},
    {t:'AGARWALEYE.NS',n:'Dr. Agarwal\'S Health Care'},
    {t:'AGI.NS',n:'Agi Greenpac'},
    {t:'AGIIL.NS',n:'Agi Infra'},
    {t:'AGRITECH.NS',n:'Agri-Tech (India)'},
    {t:'AGROPHOS.NS',n:'Agro Phos India'},
    {t:'AHCL.NS',n:'Anlon Healthcare'},
    {t:'AHLADA.NS',n:'Ahlada Engineers'},
    {t:'AHLEAST.NS',n:'Asian Hotels (East)'},
    {t:'AHLUCONT.NS',n:'Ahluwalia Contracts (India)'},
    {t:'AIAENG.NS',n:'Aia Engineering'},
    {t:'AIIL.NS',n:'Authum Investment & Infrastructure'},
    {t:'AIRAN.NS',n:'Airan'},
    {t:'AIROLAM.NS',n:'Airo Lam'},
    {t:'AJANTPHARM.NS',n:'Ajanta Pharma'},
    {t:'AJAXENGG.NS',n:'Ajax Engineering'},
    {t:'AJMERA.NS',n:'Ajmera Realty & Infra India'},
    {t:'AJOONI.NS',n:'Ajooni Biotech'},
    {t:'AKASH.NS',n:'Akash Infra-Projects'},
    {t:'AKCAPIT.NS',n:'Ak Capital Services'},
    {t:'AKG.NS',n:'Akg Exim'},
    {t:'AKI.NS',n:'Aki India'},
    {t:'AKSHAR.NS',n:'Akshar Spintex'},
    {t:'AKSHARCHEM.NS',n:'Aksharchem India'},
    {t:'AKUMS.NS',n:'Akums Drugs And Pharmaceuticals'},
    {t:'ALANKIT.NS',n:'Alankit'},
    {t:'ALBERTDAVD.NS',n:'Albert David'},
    {t:'ALEMBICLTD.NS',n:'Alembic'},
    {t:'ALGOQUANT.NS',n:'Algoquant Fintech'},
    {t:'ALICON.NS',n:'Alicon Castalloy'},
    {t:'ALIVUS.NS',n:'Alivus Life Sciences'},
    {t:'ALKALI.NS',n:'Alkali Metals'},
    {t:'ALKEM.NS',n:'Alkem'},
    {t:'ALKYLAMINE.NS',n:'Alkyl Amines Chemicals'},
    {t:'ALLCARGO.NS',n:'Allcargo Logistics'},
    {t:'ALLDIGI.NS',n:'Alldigi Tech'},
    {t:'ALLTIME.NS',n:'All Time Plastics'},
    {t:'ALMONDZ.NS',n:'Almondz Global Securities'},
    {t:'ALOKINDS.NS',n:'Alok Industries'},
    {t:'ALPA.NS',n:'Alpa Laboratories'},
    {t:'ALPHAGEO.NS',n:'Alphageo (India)'},
    {t:'AMAGI.NS',n:'Amagi Media Labs'},
    {t:'AMANTA.NS',n:'Amanta Healthcare'},
    {t:'AMARAJABAT.NS',n:'Amara Raja'},
    {t:'AMBALALSA.NS',n:'Ambalal Sarabhai Enterprises'},
    {t:'AMBER.NS',n:'Amber Enterprises India'},
    {t:'AMBICAAGAR.NS',n:'Ambica Agarbathies & Aroma Industries'},
    {t:'AMBIKCO.NS',n:'Ambika Cotton Mills'},
    {t:'AMBUJACEM.NS',n:'Ambuja'},
    {t:'AMDIND.NS',n:'Amd Industries'},
    {t:'AMIRCHAND.NS',n:'Amir Chand Jagdish Kumar (Exports)'},
    {t:'AMJLAND.NS',n:'Amj Land Holdings'},
    {t:'AMNPLST.NS',n:'Amines & Plasticizers'},
    {t:'AMRUTANJAN.NS',n:'Amrutanjan Health Care'},
    {t:'ANANDRATHI.NS',n:'Anand Rathi Wealth'},
    {t:'ANANTRAJ.NS',n:'Anant Raj'},
    {t:'ANDHRAPAP.NS',n:'Andhra Paper'},
    {t:'ANDHRSUGAR.NS',n:'The Andhra Sugars'},
    {t:'ANGELONE.NS',n:'Angel Broking'},
    {t:'ANMOL.NS',n:'Anmol India'},
    {t:'ANTELOPUS.NS',n:'Antelopus Selan Energy'},
    {t:'ANTGRAPHIC.NS',n:'Antarctica'},
    {t:'ANTHEM.NS',n:'Anthem Biosciences'},
    {t:'ANUHPHR.NS',n:'Anuh Pharma'},
    {t:'ANUP.NS',n:'The Anup Engineering'},
    {t:'ANURAS.NS',n:'Anupam Rasayan India'},
    {t:'APARINDS.NS',n:'Apar Industries'},
    {t:'APCL.NS',n:'Anjani Portland Cement'},
    {t:'APCOTEXIND.NS',n:'Apcotex Industries'},
    {t:'APEX.NS',n:'Apex Frozen Foods'},
    {t:'APLAPOLLO.NS',n:'Apl Apollo Tubes'},
    {t:'APLLTD.NS',n:'Alembic Pharmaceuticals'},
    {t:'APOLLO.NS',n:'Apollo Micro Systems'},
    {t:'APOLLOHOSP.NS',n:'Apollo'},
    {t:'APOLLOPIPE.NS',n:'Apollo Pipes'},
    {t:'APOLLOTYRE.NS',n:'Apollo Tyres'},
    {t:'APOLSINHOT.NS',n:'Apollo Sindoori Hotels'},
    {t:'APTECHT.NS',n:'Aptech'},
    {t:'APTUS.NS',n:'Aptus Value Housing Finance India'},
    {t:'AQYLON.NS',n:'Aqylon Nexus'},
    {t:'ARCHIDPLY.NS',n:'Archidply Industries'},
    {t:'ARCHIES.NS',n:'Archies'},
    {t:'ARE&M.NS',n:'Amara Raja Energy & Mobility'},
    {t:'ARENTERP.NS',n:'Rajdarshan Industries'},
    {t:'ARFIN.NS',n:'Arfin India'},
    {t:'ARIES.NS',n:'Aries Agro'},
    {t:'ARIHANT.NS',n:'Arihant Foundations & Housing'},
    {t:'ARIHANTCAP.NS',n:'Arihant Capital Markets'},
    {t:'ARIHANTSUP.NS',n:'Arihant Superstructures'},
    {t:'ARIS.NS',n:'Arisinfra Solutions'},
    {t:'ARKADE.NS',n:'Arkade Developers'},
    {t:'ARMANFIN.NS',n:'Arman Financial Services'},
    {t:'AROGRANITE.NS',n:'Aro Granite Industries'},
    {t:'ARROWGREEN.NS',n:'Arrow Greentech'},
    {t:'ARSSBL.NS',n:'Anand Rathi Share And Stock Brokers'},
    {t:'ARTEMISMED.NS',n:'Artemis Medicare Services'},
    {t:'ARTNIRMAN.NS',n:'Art Nirman'},
    {t:'ARVEE.NS',n:'Arvee Laboratories (India)'},
    {t:'ARVIND.NS',n:'Arvind'},
    {t:'ARVINDFASN.NS',n:'Arvind Fashions'},
    {t:'ARVSMART.NS',n:'Arvind Smartspaces'},
    {t:'ASAHIINDIA.NS',n:'Asahi India Glass'},
    {t:'ASAHISONG.NS',n:'Asahi Songwon Colors'},
    {t:'ASAL.NS',n:'Automotive Stampings And Assemblies'},
    {t:'ASALCBR.NS',n:'Associated Alcohols & Breweries Ltd'},
    {t:'ASHAPURMIN.NS',n:'Ashapura Minechem'},
    {t:'ASHIANA.NS',n:'Ashiana Housing'},
    {t:'ASHIKA.NS',n:'Ashika Credit Capital'},
    {t:'ASHIMASYN.NS',n:'Ashima'},
    {t:'ASHOKA.NS',n:'Ashoka Buildcon'},
    {t:'ASHOKAMET.NS',n:'Ashoka Metcast'},
    {t:'ASHOKLEY.NS',n:'Ashok Leyland'},
    {t:'ASIANENE.NS',n:'Asian Energy Services'},
    {t:'ASIANHOTNR.NS',n:'Asian Hotels (North)'},
    {t:'ASIANPAINT.NS',n:'Asian Paints'},
    {t:'ASIANTILES.NS',n:'Asian Granito India'},
    {t:'ASKAUTOLTD.NS',n:'Ask Automotive'},
    {t:'ASMS.NS',n:'Bartronics India'},
    {t:'ASPINWALL.NS',n:'Aspinwall And Company'},
    {t:'ASTAR.NS',n:'Asian Star Company'},
    {t:'ASTEC.NS',n:'Astec Lifesciences'},
    {t:'ASTERDM.NS',n:'Aster Dm Healthcare'},
    {t:'ASTRAL.NS',n:'Astral'},
    {t:'ASTRAMICRO.NS',n:'Astra Microwave Products'},
    {t:'ASTRAZEN.NS',n:'Astrazeneca Pharma India'},
    {t:'ATALREAL.NS',n:'Atal Realtech'},
    {t:'ATAM.NS',n:'Atam Valves'},
    {t:'ATGL.NS',n:'Adani Total Gas'},
    {t:'ATHERENERG.NS',n:'Ather Energy'},
    {t:'ATL.NS',n:'Allcargo Terminals'},
    {t:'ATLANTAA.NS',n:'Atlantaa'},
    {t:'ATLANTAELE.NS',n:'Atlanta Electricals'},
    {t:'ATLASCYCLE.NS',n:'Atlas Cycles (Haryana)'},
    {t:'ATUL.NS',n:'Atul'},
    {t:'ATULAUTO.NS',n:'Atul Auto'},
    {t:'AUBANK.NS',n:'Au Small Finance Bank'},
    {t:'AURIGROW.NS',n:'Auri Grow India'},
    {t:'AURIONPRO.NS',n:'Aurionpro Solutions'},
    {t:'AUROPHARMA.NS',n:'Aurobindo'},
    {t:'AURUM.NS',n:'Aurum Proptech'},
    {t:'AUTOAXLES.NS',n:'Automotive Axles'},
    {t:'AVAILFC.NS',n:'Available Finance'},
    {t:'AVALON.NS',n:'Avalon Technologies'},
    {t:'AVANTEL.NS',n:'Avantel'},
    {t:'AVANTIFEED.NS',n:'Avanti Feeds'},
    {t:'AVG.NS',n:'Avg Logistics'},
    {t:'AVL.NS',n:'Aditya Vision'},
    {t:'AVONMORE.NS',n:'Avonmore Capital & Management Services'},
    {t:'AVROIND.NS',n:'Avro India'},
    {t:'AVTNPL.NS',n:'Avt Natural Products'},
    {t:'AWFIS.NS',n:'Awfis Space Solutions'},
    {t:'AWHCL.NS',n:'Antony Waste Handling Cell'},
    {t:'AWL.NS',n:'Awl Agri Business'},
    {t:'AXISBANK.NS',n:'Axis'},
    {t:'AXISCADES.NS',n:'Axiscades Technologies'},
    {t:'AXITA.NS',n:'Axita Cotton'},
    {t:'AYE.NS',n:'Aye Finance'},
    {t:'AYMSYNTEX.NS',n:'Aym Syntex'},
    {t:'AZAD.NS',n:'Azad Engineering'},
    {t:'BAFNAPH.NS',n:'Bafna Pharmaceuticals'},
    {t:'BAGFILMS.NS',n:'B.A.G Films And Media'},
    {t:'BAIDFIN.NS',n:'Baid Finserv'},
    {t:'BAJAJ-AUTO.NS',n:'Bajaj Auto'},
    {t:'BAJAJCON.NS',n:'Bajaj Consumer'},
    {t:'BAJAJELEC.NS',n:'Bajaj Electricals'},
    {t:'BAJAJFINSV.NS',n:'Bajaj Finserv'},
    {t:'BAJAJHCARE.NS',n:'Bajaj Healthcare'},
    {t:'BAJAJHFL.NS',n:'Bajaj Housing Finance'},
    {t:'BAJAJHIND.NS',n:'Bajaj Hindusthan Sugar'},
    {t:'BAJAJHLDNG.NS',n:'Bajaj Holdings & Investment'},
    {t:'BAJAJINDEF.NS',n:'Indef Manufacturing'},
    {t:'BAJAJST.NS',n:'Bajaj Steel Industries'},
    {t:'BAJEL.NS',n:'Bajel Projects'},
    {t:'BAJFINANCE.NS',n:'Bajaj Finance'},
    {t:'BALAJEE.NS',n:'Shree Tirupati Balajee Agro Trading Company'},
    {t:'BALAJITELE.NS',n:'Balaji Telefilms'},
    {t:'BALAMINES.NS',n:'Balaji Amines'},
    {t:'BALKRISHNA.NS',n:'Balkrishna Paper Mills'},
    {t:'BALKRISIND.NS',n:'Balkrishna Industries'},
    {t:'BALMLAWRIE.NS',n:'Balmer Lawrie & Company'},
    {t:'BALPHARMA.NS',n:'Bal Pharma'},
    {t:'BALRAMCHIN.NS',n:'Balrampur Chini Mills'},
    {t:'BALUFORGE.NS',n:'Balu Forge Industries'},
    {t:'BANARBEADS.NS',n:'Banaras Beads'},
    {t:'BANARISUG.NS',n:'Bannari Amman Sugars'},
    {t:'BANCOINDIA.NS',n:'Banco Products (I)'},
    {t:'BANDHANBNK.NS',n:'Bandhan'},
    {t:'BANG.NS',n:'Bang Overseas'},
    {t:'BANKBARODA.NS',n:'Bob'},
    {t:'BANKINDIA.NS',n:'Bank Of India'},
    {t:'BANSALWIRE.NS',n:'Bansal Wire Industries'},
    {t:'BANSWRAS.NS',n:'Banswara Syntex'},
    {t:'BASF.NS',n:'Basf India'},
    {t:'BASML.NS',n:'Bannari Amman Spinning Mills'},
    {t:'BATAIND.NS',n:'Bata India'},
    {t:'BATAINDIA.NS',n:'Bata India'},
    {t:'BATLIBOI.NS',n:'Batliboi'},
    {t:'BAYERCROP.NS',n:'Bayer Cropscience'},
    {t:'BBL.NS',n:'Bharat Bijlee'},
    {t:'BBOX.NS',n:'Black Box'},
    {t:'BBTC.NS',n:'Bombay Burmah'},
    {t:'BBTCL.NS',n:'B&B Triplewall Containers'},
    {t:'BCG.NS',n:'Brightcom Group'},
    {t:'BCLIND.NS',n:'Bcl Industries'},
    {t:'BCONCEPTS.NS',n:'Brand Concepts'},
    {t:'BCPL.NS',n:'Bcpl Railway Infrastructure'},
    {t:'BDL.NS',n:'Bharat Dynamics'},
    {t:'BEARDSELL.NS',n:'Beardsell'},
    {t:'BECTORFOOD.NS',n:'Mrs. Bectors Food Specialities'},
    {t:'BEDMUTHA.NS',n:'Bedmutha Industries'},
    {t:'BEEKAY.NS',n:'Beekay Steel Industries'},
    {t:'BEL.NS',n:'Bel'},
    {t:'BELLACASA.NS',n:'Bella Casa Fashion & Retail'},
    {t:'BELRISE.NS',n:'Belrise Industries'},
    {t:'BEML.NS',n:'Beml'},
    {t:'BENGALASM.NS',n:'Bengal & Assam Company'},
    {t:'BEPL.NS',n:'Bhansali Engineering Polymers'},
    {t:'BERGEPAINT.NS',n:'Berger Paints (I)'},
    {t:'BESTAGRO.NS',n:'Best Agrolife'},
    {t:'BETA.NS',n:'Beta Drugs'},
    {t:'BFINVEST.NS',n:'Bf Investment'},
    {t:'BFUTILITIE.NS',n:'Bf Utilities'},
    {t:'BHAGCHEM.NS',n:'Bhagiradha Chemicals & Industries'},
    {t:'BHAGERIA.NS',n:'Bhageria Industries'},
    {t:'BHARATCOAL.NS',n:'Bharat Coking Coal'},
    {t:'BHARATFORG.NS',n:'Bharat Forge'},
    {t:'BHARATGEAR.NS',n:'Bharat Gears'},
    {t:'BHARATRAS.NS',n:'Bharat Rasayan'},
    {t:'BHARATSE.NS',n:'Bharat Seats'},
    {t:'BHARATWIRE.NS',n:'Bharat Wire Ropes'},
    {t:'BHARTIARTL.NS',n:'Airtel'},
    {t:'BHARTIHEXA.NS',n:'Bharti Hexacom'},
    {t:'BHEL.NS',n:'Bharat Heavy Electricals'},
    {t:'BI.NS',n:'Bilcare'},
    {t:'BIGBLOC.NS',n:'Bigbloc Construction'},
    {t:'BIKAJI.NS',n:'Bikaji Foods International'},
    {t:'BIL.NS',n:'Bhartiya International'},
    {t:'BIMETAL.NS',n:'Bimetal Bearings'},
    {t:'BIOCON.NS',n:'Biocon'},
    {t:'BIOFILCHEM.NS',n:'Biofil Chemicals & Pharmaceuticals'},
    {t:'BIRLACORPN.NS',n:'Birla Corporation'},
    {t:'BIRLAMONEY.NS',n:'Aditya Birla Money'},
    {t:'BIRLANU.NS',n:'Birlanu'},
    {t:'BIRLAPREC.NS',n:'Birla Precision Technologies'},
    {t:'BLACKBUCK.NS',n:'Blackbuck'},
    {t:'BLACKROSE.NS',n:'Black Rose Inds.'},
    {t:'BLAL.NS',n:'Beml Land Assets'},
    {t:'BLIL.NS',n:'Balmer Lawrie Investments'},
    {t:'BLISSGVS.NS',n:'Bliss Gvs Pharma'},
    {t:'BLKASHYAP.NS',n:'B. L. Kashyap And Sons'},
    {t:'BLS.NS',n:'Bls International Services'},
    {t:'BLSE.NS',n:'Bls E-Services'},
    {t:'BLUECHIP.NS',n:'Blue Chip India'},
    {t:'BLUEDART.NS',n:'Blue Dart Express'},
    {t:'BLUEJET.NS',n:'Blue Jet Healthcare'},
    {t:'BLUESTARCO.NS',n:'Blue Star'},
    {t:'BLUESTONE.NS',n:'Bluestone Jewellery And Lifestyle'},
    {t:'BLUSPRING.NS',n:'Bluspring Enterprises'},
    {t:'BMWVENTLTD.NS',n:'Bmw Ventures'},
    {t:'BNALTD.NS',n:'B & A'},
    {t:'BODALCHEM.NS',n:'Bodal Chemicals'},
    {t:'BOMDYEING.NS',n:'Bombay Dyeing & Mfg Company'},
    {t:'BONLON.NS',n:'Bonlon Industries'},
    {t:'BORANA.NS',n:'Borana Weaves'},
    {t:'BOROLTD.NS',n:'Borosil'},
    {t:'BORORENEW.NS',n:'Borosil Renewables'},
    {t:'BOROSCI.NS',n:'Borosil Scientific'},
    {t:'BOSCH-HCIL.NS',n:'Bosch Home Comfort India'},
    {t:'BOSCHLTD.NS',n:'Bosch'},
    {t:'BPCL.NS',n:'Bpcl'},
    {t:'BPL.NS',n:'Bpl'},
    {t:'BRIGADE.NS',n:'Brigade Enterprises'},
    {t:'BRIGHOTEL.NS',n:'Brigade Hotel Ventures'},
    {t:'BRITANNIA.NS',n:'Britannia'},
    {t:'BRNL.NS',n:'Bharat Road Network'},
    {t:'BSE.NS',n:'Bse'},
    {t:'BSL.NS',n:'Bsl'},
    {t:'BSOFT.NS',n:'Birlasoft'},
    {t:'BTML.NS',n:'Bodhi Tree Multimedia'},
    {t:'BTTL.NS',n:'Bhilwara Technical Textiles'},
    {t:'BUILDPRO.NS',n:'Shankara Buildpro'},
    {t:'BUTTERFLY.NS',n:'Butterfly Gandhimathi Appliances'},
    {t:'BVCL.NS',n:'Barak Valley Cements'},
    {t:'BYKE.NS',n:'The Byke Hospitality Ltd'},
    {t:'CAMLINFINE.NS',n:'Camlin Fine Sciences'},
    {t:'CAMPUS.NS',n:'Campus Activewear'},
    {t:'CAMS.NS',n:'Cams'},
    {t:'CANBK.NS',n:'Canara'},
    {t:'CANFINHOME.NS',n:'Can Fin Homes'},
    {t:'CANHLIFE.NS',n:'Canara Hsbc Life Insurance Company'},
    {t:'CANTABIL.NS',n:'Cantabil Retail India'},
    {t:'CAPACITE.NS',n:'Capacit\'E Infraprojects'},
    {t:'CAPILLARY.NS',n:'Capillary Technologies India'},
    {t:'CAPITALSFB.NS',n:'Capital Small Finance Bank'},
    {t:'CAPLIPOINT.NS',n:'Caplin Point Laboratories'},
    {t:'CARBORUNIV.NS',n:'Carborundum Universal'},
    {t:'CARERATING.NS',n:'Care Ratings'},
    {t:'CARRARO.NS',n:'Carraro India'},
    {t:'CARTRADE.NS',n:'Cartrade Tech'},
    {t:'CARYSIL.NS',n:'Carysil'},
    {t:'CASTROLIND.NS',n:'Castrol India'},
    {t:'CCAVENUE.NS',n:'Avenuesai'},
    {t:'CCCL.NS',n:'Consolidated Construction Consortium'},
    {t:'CCHHL.NS',n:'Country Club Hospitality & Holidays'},
    {t:'CCL.NS',n:'Ccl Products (India)'},
    {t:'CDSL.NS',n:'Cdsl'},
    {t:'CEATLTD.NS',n:'Ceat'},
    {t:'CEIGALL.NS',n:'Ceigall India'},
    {t:'CEINSYS.NS',n:'Ceinsys Tech'},
    {t:'CELEBRITY.NS',n:'Celebrity Fashions'},
    {t:'CELLO.NS',n:'Cello World'},
    {t:'CEMPRO.NS',n:'Cemindia Projects'},
    {t:'CENTENKA.NS',n:'Century Enka'},
    {t:'CENTEXT.NS',n:'Century Extrusions'},
    {t:'CENTRALBK.NS',n:'Central Bank Of India'},
    {t:'CENTRUM.NS',n:'Centrum Capital'},
    {t:'CENTUM.NS',n:'Centum Electronics'},
    {t:'CENTURYPLY.NS',n:'Century Plyboards (India)'},
    {t:'CERA.NS',n:'Cera Sanitaryware'},
    {t:'CESC.NS',n:'Cesc'},
    {t:'CEWATER.NS',n:'Concord Enviro Systems'},
    {t:'CGCL.NS',n:'Capri Global Capital'},
    {t:'CGPOWER.NS',n:'Cg Power And Industrial Solutions'},
    {t:'CHALET.NS',n:'Chalet Hotels'},
    {t:'CHAMBLFERT.NS',n:'Chambal Fertilizers & Chemicals'},
    {t:'CHEMCON.NS',n:'Chemcon Speciality Chemicals'},
    {t:'CHEMPLASTS.NS',n:'Chemplast Sanmar'},
    {t:'CHENNPETRO.NS',n:'Chennai Petroleum Corporation'},
    {t:'CHEVIOT.NS',n:'Cheviot Company'},
    {t:'CHOICEIN.NS',n:'Choice International'},
    {t:'CHOLAFIN.NS',n:'Chola'},
    {t:'CHOLAHLDNG.NS',n:'Cholamandalam Financial Holdings'},
    {t:'CIEINDIA.NS',n:'Cie Automotive India'},
    {t:'CIFL.NS',n:'Capital India Finance'},
    {t:'CINELINE.NS',n:'Cineline India'},
    {t:'CINEVISTA.NS',n:'Cinevista'},
    {t:'CIPLA.NS',n:'Cipla'},
    {t:'CLEAN.NS',n:'Clean Science And Technology'},
    {t:'CLEANMAX.NS',n:'Clean Max Enviro Energy Solutions'},
    {t:'CLEANSCI.NS',n:'Clean Science'},
    {t:'CLEDUCATE.NS',n:'Cl Educate'},
    {t:'CLSEL.NS',n:'Chaman Lal Setia Exports'},
    {t:'CMPDI.NS',n:'Central Mine Planning & Design Institute'},
    {t:'CMSINFO.NS',n:'Cms Info Systems'},
    {t:'CNL.NS',n:'Creative Newtech'},
    {t:'COALINDIA.NS',n:'Coal India'},
    {t:'COASTCORP.NS',n:'Coastal Corporation'},
    {t:'COCHINSHIP.NS',n:'Cochin Shipyard'},
    {t:'COCKERILL.NS',n:'John Cockerill India'},
    {t:'COFFEEDAY.NS',n:'Coffee Day Enterprises'},
    {t:'COFORGE.NS',n:'Coforge'},
    {t:'COHANCE.NS',n:'Cohance Lifesciences'},
    {t:'COLPAL.NS',n:'Colgate'},
    {t:'COMFINTE.NS',n:'Comfort Intech'},
    {t:'COMPUSOFT.NS',n:'Compucom Software'},
    {t:'COMSYN.NS',n:'Commercial Syn Bags'},
    {t:'CONCOR.NS',n:'Container Corporation Of India'},
    {t:'CONCORDBIO.NS',n:'Concord Biotech'},
    {t:'CONFIPET.NS',n:'Confidence Petroleum India'},
    {t:'CONSOFINVT.NS',n:'Consolidated Finvest & Holdings'},
    {t:'CONTROLPR.NS',n:'Control Print'},
    {t:'CORALFINAC.NS',n:'Coral India Finance & Housing'},
    {t:'CORDSCABLE.NS',n:'Cords Cable Industries'},
    {t:'COROMANDEL.NS',n:'Coromandel International'},
    {t:'CORONA.NS',n:'Corona Remedies'},
    {t:'COSMOFIRST.NS',n:'Cosmo First'},
    {t:'COUNCODOS.NS',n:'Country Condo\'S'},
    {t:'CPEDU.NS',n:'Career Point Edutech'},
    {t:'CPPLUS.NS',n:'Aditya Infotech'},
    {t:'CRAFTSMAN.NS',n:'Craftsman Automation'},
    {t:'CRAMC.NS',n:'Canara Robeco Asset Management Company'},
    {t:'CREATIVEYE.NS',n:'Creative Eye'},
    {t:'CREDITACC.NS',n:'Creditaccess Grameen'},
    {t:'CREST.NS',n:'Crest Ventures'},
    {t:'CRISIL.NS',n:'Crisil'},
    {t:'CRIZAC.NS',n:'Crizac'},
    {t:'CROMPTON.NS',n:'Crompton Greaves Consumer Electricals'},
    {t:'CROWN.NS',n:'Crown Lifters'},
    {t:'CSBBANK.NS',n:'Csb Bank'},
    {t:'CSLFINANCE.NS',n:'Csl Finance'},
    {t:'CTE.NS',n:'Cambridge Technology Enterprises'},
    {t:'CUB.NS',n:'City Union Bank'},
    {t:'CUBEXTUB.NS',n:'Cubex Tubings'},
    {t:'CUMMINSIND.NS',n:'Cummins India'},
    {t:'CUPID.NS',n:'Cupid'},
    {t:'CYBERTECH.NS',n:'Cybertech Systems And Software'},
    {t:'CYIENT.NS',n:'Cyient'},
    {t:'CYIENTDLM.NS',n:'Cyient Dlm'},
    {t:'DABUR.NS',n:'Dabur'},
    {t:'DAICHI.NS',n:'Dai-Ichi Karkaria'},
    {t:'DALBHARAT.NS',n:'Dalmia'},
    {t:'DALMIASUG.NS',n:'Dalmia Bharat Sugar And Industries'},
    {t:'DAMCAPITAL.NS',n:'Dam Capital Advisors'},
    {t:'DAMODARIND.NS',n:'Damodar Industries'},
    {t:'DANGEE.NS',n:'Dangee Dums'},
    {t:'DATAMATICS.NS',n:'Datamatics Global Services'},
    {t:'DATAPATTNS.NS',n:'Data Patterns (India)'},
    {t:'DAVANGERE.NS',n:'Davangere Sugar Company'},
    {t:'DBCORP.NS',n:'D.B.Corp'},
    {t:'DBEIL.NS',n:'Deepak Builders & Engineers India'},
    {t:'DBL.NS',n:'Dilip Buildcon'},
    {t:'DBSTOCKBRO.NS',n:'Db (International) Stock Brokers'},
    {t:'DCAL.NS',n:'Dishman Carbogen Amcis'},
    {t:'DCBBANK.NS',n:'Dcb Bank'},
    {t:'DCM.NS',n:'Dcm'},
    {t:'DCMSHRIRAM.NS',n:'Dcm Shriram'},
    {t:'DCMSRIND.NS',n:'Dcm Shriram Industries'},
    {t:'DCW.NS',n:'Dcw'},
    {t:'DCXINDIA.NS',n:'Dcx Systems'},
    {t:'DDEVPLSTIK.NS',n:'Ddev Plastiks Industries'},
    {t:'DECCANCE.NS',n:'Deccan Cements'},
    {t:'DECNGOLD.NS',n:'Deccan Gold Mines'},
    {t:'DEEPAKFERT.NS',n:'Deepak Fertilizers And Petrochemicals Corporation'},
    {t:'DEEPAKNTR.NS',n:'Deepak'},
    {t:'DEEPINDS.NS',n:'Deep Industries'},
    {t:'DELHIVERY.NS',n:'Delhivery'},
    {t:'DELPHIFX.NS',n:'Delphi World Money'},
    {t:'DELTACORP.NS',n:'Delta Corp'},
    {t:'DELTAMAGNT.NS',n:'Delta Manufacturing'},
    {t:'DEN.NS',n:'Den Networks'},
    {t:'DENORA.NS',n:'De Nora India'},
    {t:'DENTA.NS',n:'Denta Water And Infra Solutions'},
    {t:'DEVIT.NS',n:'Dev Information Technology'},
    {t:'DEVX.NS',n:'Dev Accelerator'},
    {t:'DEVYANI.NS',n:'Devyani International'},
    {t:'DGCONTENT.NS',n:'Digicontent'},
    {t:'DHAMPURSUG.NS',n:'Dhampur Sugar Mills'},
    {t:'DHANBANK.NS',n:'Dhanlaxmi Bank'},
    {t:'DHANUKA.NS',n:'Dhanuka Agritech'},
    {t:'DHARMAJ.NS',n:'Dharmaj Crop Guard'},
    {t:'DHUNINV.NS',n:'Dhunseri Investments'},
    {t:'DIACABS.NS',n:'Diamond Power Infrastructure'},
    {t:'DIAMINESQ.NS',n:'Diamines & Chemicals'},
    {t:'DIAMONDYD.NS',n:'Prataap Snacks'},
    {t:'DICIND.NS',n:'Dic India'},
    {t:'DIFFNKG.NS',n:'Diffusion Engineers'},
    {t:'DIGIDRIVE.NS',n:'Digidrive Distributors'},
    {t:'DIGITIDE.NS',n:'Digitide Solutions'},
    {t:'DIGJAMLMTD.NS',n:'Digjam'},
    {t:'DISAQ.NS',n:'Disa India'},
    {t:'DIVGIITTS.NS',n:'Divgi Torqtransfer Systems'},
    {t:'DIVISLAB.NS',n:'Divis'},
    {t:'DIXON.NS',n:'Dixon'},
    {t:'DJML.NS',n:'Dj Mediaprint & Logistics'},
    {t:'DLF.NS',n:'Dlf'},
    {t:'DLINKINDIA.NS',n:'D-Link (India)'},
    {t:'DMART.NS',n:'Avenue Supermarts'},
    {t:'DMCC.NS',n:'Dmcc Speciality Chemicals'},
    {t:'DNAMEDIA.NS',n:'Diligent Media Corporation'},
    {t:'DODLA.NS',n:'Dodla Dairy'},
    {t:'DOLATALGO.NS',n:'Dolat Algotech'},
    {t:'DOLLAR.NS',n:'Dollar Industries'},
    {t:'DOLPHIN.NS',n:'Dolphin Offshore Enterprises (India)'},
    {t:'DOMS.NS',n:'Doms Industries'},
    {t:'DONEAR.NS',n:'Donear Industries'},
    {t:'DPABHUSHAN.NS',n:'D. P. Abhushan'},
    {t:'DPWIRES.NS',n:'D P Wires'},
    {t:'DRAGARWQ.NS',n:'Dr Agarwals Eye Hospital'},
    {t:'DRCSYSTEMS.NS',n:'Drc Systems India'},
    {t:'DREAMFOLKS.NS',n:'Dreamfolks Services'},
    {t:'DREDGECORP.NS',n:'Dredging Corporation Of India'},
    {t:'DRREDDY.NS',n:'Dr Reddys'},
    {t:'DSFCL.NS',n:'Dcm Shriram Fine Chemicals'},
    {t:'DSSL.NS',n:'Dynacons Systems & Solutions'},
    {t:'DTIL.NS',n:'Dhunseri Tea & Industries'},
    {t:'DVL.NS',n:'Dhunseri Ventures'},
    {t:'DWARKESH.NS',n:'Dwarikesh Sugar Industries'},
    {t:'DYCL.NS',n:'Dynamic Cables'},
    {t:'DYNAMATECH.NS',n:'Dynamatic Technologies'},
    {t:'DYNPRO.NS',n:'Dynemic Products'},
    {t:'E2E.NS',n:'E2E Networks'},
    {t:'EASEMYTRIP.NS',n:'Easy Trip Planners'},
    {t:'EBGNG.NS',n:'Gng Electronics'},
    {t:'ECLERX.NS',n:'Eclerx Services'},
    {t:'ECOSMOBLTY.NS',n:'Ecos (India) Mobility & Hospitality'},
    {t:'EDELWEISS.NS',n:'Edelweiss'},
    {t:'EFCIL.NS',n:'Efc (I)'},
    {t:'EICHERMOT.NS',n:'Royal Enfield'},
    {t:'EIDPARRY.NS',n:'Eid Parry India'},
    {t:'EIEL.NS',n:'Enviro Infra Engineers'},
    {t:'EIFFL.NS',n:'Euro India Fresh Foods'},
    {t:'EIHAHOTELS.NS',n:'Eih Associated Hotels'},
    {t:'EIHOTEL.NS',n:'Eih'},
    {t:'EIMCOELECO.NS',n:'Eimco Elecon (India)'},
    {t:'EKC.NS',n:'Everest Kanto Cylinder'},
    {t:'ELANTAS.NS',n:'Elantas Beck India'},
    {t:'ELCIDIN.NS',n:'El Cid Investments'},
    {t:'ELDEHSG.NS',n:'Eldeco Housing And Industries'},
    {t:'ELECON.NS',n:'Elecon Engineering Company'},
    {t:'ELECTCAST.NS',n:'Electrosteel Castings'},
    {t:'ELECTHERM.NS',n:'Electrotherm (India)'},
    {t:'ELGIEQUIP.NS',n:'Elgi Equipments'},
    {t:'ELGIRUBCO.NS',n:'Elgi Rubber Company'},
    {t:'ELIN.NS',n:'Elin Electronics'},
    {t:'ELITECON.NS',n:'Elitecon International'},
    {t:'ELLEN.NS',n:'Ellenbarrie Industrial Gases'},
    {t:'ELPROINTL.NS',n:'Elpro International'},
    {t:'EMAMILTD.NS',n:'Emami'},
    {t:'EMAMIPAP.NS',n:'Emami Paper Mills'},
    {t:'EMBDL.NS',n:'Embassy Developments'},
    {t:'EMCURE.NS',n:'Emcure Pharmaceuticals'},
    {t:'EMIL.NS',n:'Electronics Mart India'},
    {t:'EMKAY.NS',n:'Emkay Global Financial Services'},
    {t:'EMMBI.NS',n:'Emmbi Industries'},
    {t:'EMMVEE.NS',n:'Emmvee Photovoltaic Power'},
    {t:'EMSLIMITED.NS',n:'Ems'},
    {t:'EMUDHRA.NS',n:'Emudhra'},
    {t:'ENDURANCE.NS',n:'Endurance Technologies'},
    {t:'ENERGYDEV.NS',n:'Energy Development Company'},
    {t:'ENGINERSIN.NS',n:'Engineers India'},
    {t:'ENIL.NS',n:'Entertainment Network (India)'},
    {t:'ENRIN.NS',n:'Siemens Energy India'},
    {t:'ENTERO.NS',n:'Entero Healthcare Solutions'},
    {t:'EPACK.NS',n:'Epack Durable'},
    {t:'EPACKPEB.NS',n:'Epack Prefab Technologies'},
    {t:'EPIGRAL.NS',n:'Epigral'},
    {t:'EPL.NS',n:'Epl'},
    {t:'EQUITASBNK.NS',n:'Equitas Small Finance Bank'},
    {t:'ERIS.NS',n:'Eris Lifesciences'},
    {t:'ESABINDIA.NS',n:'Esab India'},
    {t:'ESAFSFB.NS',n:'Esaf Small Finance Bank'},
    {t:'ESCORTS.NS',n:'Escorts Kubota'},
    {t:'ESSARSHPNG.NS',n:'Essar Shipping'},
    {t:'ESTER.NS',n:'Ester Industries'},
    {t:'ETERNAL.NS',n:'Eternal'},
    {t:'ETHOSLTD.NS',n:'Ethos'},
    {t:'EUREKAFORB.NS',n:'Eureka Forbes'},
    {t:'EUROBOND.NS',n:'Euro Panel Products'},
    {t:'EUROPRATIK.NS',n:'Euro Pratik Sales'},
    {t:'EUROTEXIND.NS',n:'Eurotex Industries And Exports'},
    {t:'EVEREADY.NS',n:'Eveready Industries India'},
    {t:'EVERESTIND.NS',n:'Everest Industries'},
    {t:'EXCELINDUS.NS',n:'Excel Industries'},
    {t:'EXCELSOFT.NS',n:'Excelsoft Technologies'},
    {t:'EXICOM.NS',n:'Exicom Tele-Systems'},
    {t:'EXIDEIND.NS',n:'Exide'},
    {t:'EXPLEOSOL.NS',n:'Expleo Solutions'},
    {t:'EXXARO.NS',n:'Exxaro Tiles'},
    {t:'FABTECH.NS',n:'Fabtech Technologies'},
    {t:'FACT.NS',n:'Fertilizers And Chemicals Travancore'},
    {t:'FAIRCHEMOR.NS',n:'Fairchem Organics'},
    {t:'FAZE3Q.NS',n:'Faze Three'},
    {t:'FCL.NS',n:'Fineotex Chemical'},
    {t:'FDC.NS',n:'Fdc'},
    {t:'FEDDERSHOL.NS',n:'Fedders Holding'},
    {t:'FEDERALBNK.NS',n:'Federal Bank'},
    {t:'FEDFINA.NS',n:'Fedbank Financial Services'},
    {t:'FERMENTA.NS',n:'Fermenta Biotech'},
    {t:'FIBERWEB.NS',n:'Fiberweb (India)'},
    {t:'FIEMIND.NS',n:'Fiem Industries'},
    {t:'FILATEX.NS',n:'Filatex India'},
    {t:'FINCABLES.NS',n:'Finolex Cables'},
    {t:'FINEORG.NS',n:'Fine Organics'},
    {t:'FINKURVE.NS',n:'Finkurve Financial Services'},
    {t:'FINOPB.NS',n:'Fino Payments Bank'},
    {t:'FINPIPE.NS',n:'Finolex Industries'},
    {t:'FIRSTCRY.NS',n:'Brainbees Solutions'},
    {t:'FISCHER.NS',n:'Fischer Medical Ventures'},
    {t:'FIVESTAR.NS',n:'Five-Star Business Finance'},
    {t:'FLAIR.NS',n:'Flair Writing Industries'},
    {t:'FLEXITUFF.NS',n:'Flexituff Ventures International'},
    {t:'FLUOROCHEM.NS',n:'Gujarat Fluorochemicals'},
    {t:'FMGOETZE.NS',n:'Federal-Mogul Goetze (India).'},
    {t:'FMNL.NS',n:'Future Market Networks'},
    {t:'FOCUS.NS',n:'Focus Lighting And Fixtures'},
    {t:'FOODSIN.NS',n:'Foods & Inns'},
    {t:'FORCEMOT.NS',n:'Force Motors Ltd'},
    {t:'FORTIS.NS',n:'Fortis Healthcare'},
    {t:'FOSECOIND.NS',n:'Foseco India'},
    {t:'FRACTAL.NS',n:'Fractal Analytics'},
    {t:'FRONTSP.NS',n:'Frontier Springs'},
    {t:'FSL.NS',n:'Firstsource Solutions'},
    {t:'FUSION.NS',n:'Fusion Finance'},
    {t:'GABRIEL.NS',n:'Gabriel India'},
    {t:'GAEL.NS',n:'Gujarat Ambuja Exports'},
    {t:'GAIL.NS',n:'Gail (India)'},
    {t:'GALAPREC.NS',n:'Gala Precision Engineering'},
    {t:'GALAXYSURF.NS',n:'Galaxy Surfactants'},
    {t:'GALLANTT.NS',n:'Gallantt Ispat'},
    {t:'GANDHAR.NS',n:'Gandhar Oil Refinery (India)'},
    {t:'GANDHITUBE.NS',n:'Gandhi Special Tubes'},
    {t:'GANECOS.NS',n:'Ganesha Ecosphere'},
    {t:'GANESHBE.NS',n:'Ganesh Benzoplast'},
    {t:'GANESHCP.NS',n:'Ganesh Consumer Products'},
    {t:'GANESHHOU.NS',n:'Ganesh Housing'},
    {t:'GANGAFORGE.NS',n:'Ganga Forging'},
    {t:'GANGESSECU.NS',n:'Ganges Securities'},
    {t:'GARFIBRES.NS',n:'Garware Technical Fibres'},
    {t:'GARUDA.NS',n:'Garuda Construction And Engineering'},
    {t:'GATECH.NS',n:'Gacm Technologies'},
    {t:'GATECHDVR.NS',n:'Gacm Technologies'},
    {t:'GATEWAY.NS',n:'Gateway Distriparks'},
    {t:'GAYAHWS.NS',n:'Gayatri Highways'},
    {t:'GCSL.NS',n:'Gretex Corporate Services'},
    {t:'GEECEE.NS',n:'Geecee Ventures'},
    {t:'GEEKAYWIRE.NS',n:'Geekay Wires'},
    {t:'GENCON.NS',n:'Generic Engineering Construction And Projects'},
    {t:'GENESYS.NS',n:'Genesys International Corporation'},
    {t:'GENUSPAPER.NS',n:'Genus Paper & Boards'},
    {t:'GENUSPOWER.NS',n:'Genus Power Infrastructures'},
    {t:'GEOJITFSL.NS',n:'Geojit Financial Services'},
    {t:'GESHIP.NS',n:'The Great Eastern Shipping Company'},
    {t:'GFLLIMITED.NS',n:'Gfl'},
    {t:'GHCL.NS',n:'Ghcl'},
    {t:'GHCLTEXTIL.NS',n:'Ghcl Textiles'},
    {t:'GICHSGFIN.NS',n:'Gic Housing Finance'},
    {t:'GICL.NS',n:'Globe International Carriers'},
    {t:'GICRE.NS',n:'General Insurance Corporation Of India'},
    {t:'GILLANDERS.NS',n:'Gillanders Arbuthnot & Company'},
    {t:'GILLETTE.NS',n:'Gillette India'},
    {t:'GINNIFILA.NS',n:'Ginni Filaments'},
    {t:'GIPCL.NS',n:'Gujarat Industries Power Company'},
    {t:'GKENERGY.NS',n:'Gk Energy'},
    {t:'GKSL.NS',n:'Gujarat Kidney And Super Speciality'},
    {t:'GKWLIMITED.NS',n:'Gkw'},
    {t:'GLAND.NS',n:'Gland Pharma'},
    {t:'GLAXO.NS',n:'Glaxosmithkline Pharmaceuticals'},
    {t:'GLENMARK.NS',n:'Glenmark Pharmaceuticals'},
    {t:'GLOBAL.NS',n:'Global Education'},
    {t:'GLOBALVECT.NS',n:'Global Vectra Helicorp'},
    {t:'GLOBE.NS',n:'Globe Enterprises (India)'},
    {t:'GLOBUSSPR.NS',n:'Globus Spirits'},
    {t:'GLOSTERLTD.NS',n:'Gloster'},
    {t:'GLOTTIS.NS',n:'Glottis'},
    {t:'GMBREW.NS',n:'Gm Breweries'},
    {t:'GMDCLTD.NS',n:'Gujarat Mineral Development Corporation'},
    {t:'GMMPFAUDLR.NS',n:'Gmm Pfaudler'},
    {t:'GMRAIRPORT.NS',n:'Gmr Airports'},
    {t:'GMRP&UI.NS',n:'Gmr Power And Urban Infra'},
    {t:'GNA.NS',n:'Gna Axles'},
    {t:'GNFC.NS',n:'Gujarat Narmada Valley Fertilizers And Chemicals'},
    {t:'GNRL.NS',n:'Gujarat Natural Resources'},
    {t:'GOACARBON.NS',n:'Goa Carbon'},
    {t:'GOCLCORP.NS',n:'Gocl Corporation'},
    {t:'GOCOLORS.NS',n:'Go Fashion (India)'},
    {t:'GODAVARIB.NS',n:'Godavari Biorefineries'},
    {t:'GODFRYPHLP.NS',n:'Godfrey Phillips'},
    {t:'GODIGIT.NS',n:'Go Digit General Insurance'},
    {t:'GODREJAGRO.NS',n:'Godrej Agrovet'},
    {t:'GODREJCP.NS',n:'Godrej'},
    {t:'GODREJIND.NS',n:'Godrej Industries'},
    {t:'GODREJPROP.NS',n:'Godrej Properties'},
    {t:'GOKEX.NS',n:'Gokaldas Exports'},
    {t:'GOKUL.NS',n:'Gokul Refoils And Solvent'},
    {t:'GOKULAGRO.NS',n:'Gokul Agro Resources'},
    {t:'GOLDIAM.NS',n:'Goldiam International'},
    {t:'GOLDTECH.NS',n:'Aion-Tech Solutions'},
    {t:'GOODLUCK.NS',n:'Goodluck India'},
    {t:'GOODYEAR.NS',n:'Goodyear India'},
    {t:'GOPAL.NS',n:'Gopal Snacks'},
    {t:'GOYALALUM.NS',n:'Goyal Aluminiums'},
    {t:'GPIL.NS',n:'Godawari Power And Ispat'},
    {t:'GPPL.NS',n:'Gujarat Pipavav Port'},
    {t:'GPTHEALTH.NS',n:'Gpt Healthcare'},
    {t:'GPTINFRA.NS',n:'Gpt Infraprojects'},
    {t:'GRADIENTE.NS',n:'Gradiente Infotainment'},
    {t:'GRANDOAK.NS',n:'Grand Oak Canyons Distillery'},
    {t:'GRANULES.NS',n:'Granules India'},
    {t:'GRAPHITE.NS',n:'Graphite India'},
    {t:'GRASIM.NS',n:'Grasim'},
    {t:'GRAUWEIL.NS',n:'Grauer & Weil India'},
    {t:'GRAVISSHO.NS',n:'Graviss Hospitality'},
    {t:'GRAVITA.NS',n:'Gravita India'},
    {t:'GREAVESCOT.NS',n:'Greaves Cotton'},
    {t:'GREENLAM.NS',n:'Greenlam Industries'},
    {t:'GREENPANEL.NS',n:'Greenpanel Industries'},
    {t:'GREENPLY.NS',n:'Greenply Industries'},
    {t:'GREENPOWER.NS',n:'Orient Green Power Company'},
    {t:'GRINDWELL.NS',n:'Grindwell Norton'},
    {t:'GRINFRA.NS',n:'G R Infraprojects'},
    {t:'GRMOVER.NS',n:'Grm Overseas'},
    {t:'GROBTEA.NS',n:'The Grob Tea Company'},
    {t:'GROWW.NS',n:'Billionbrains Garage Ventures'},
    {t:'GRPLTD.NS',n:'Grp'},
    {t:'GRSE.NS',n:'Garden Reach Shipbuilders & Engineers'},
    {t:'GRWRHITECH.NS',n:'Garware Hi-Tech Films'},
    {t:'GSFC.NS',n:'Gujarat State Fertilizers & Chemicals'},
    {t:'GSLSU.NS',n:'Global Surfaces'},
    {t:'GSPCROP.NS',n:'Gsp Crop Science'},
    {t:'GTECJAINX.NS',n:'G-Tec Jainx Education'},
    {t:'GTL.NS',n:'Gtl'},
    {t:'GTLINFRA.NS',n:'Gtl Infrastructure'},
    {t:'GTPL.NS',n:'Gtpl Hathway'},
    {t:'GUFICBIO.NS',n:'Gufic Biosciences'},
    {t:'GUJALKALI.NS',n:'Gujarat Alkalies And Chemicals'},
    {t:'GUJAPOLLO.NS',n:'Gujarat Apollo Industries'},
    {t:'GUJGASLTD.NS',n:'Gujarat Gas'},
    {t:'GUJRAFFIA.NS',n:'Gujarat Raffia Industries'},
    {t:'GUJTHEM.NS',n:'Gujarat Themis Biosyn'},
    {t:'GULFOILLUB.NS',n:'Gulf Oil Lubricants India'},
    {t:'GULFPETRO.NS',n:'Gp Petroleums'},
    {t:'GULPOLY.NS',n:'Gulshan Polyols'},
    {t:'GVPIL.NS',n:'Ge Power India'},
    {t:'GVPTECH.NS',n:'Gvp Infotech'},
    {t:'GVT&D.NS',n:'Ge Vernova T&D India'},
    {t:'HAL.NS',n:'Hal'},
    {t:'HALDER.NS',n:'Halder Venture'},
    {t:'HALDYNGL.NS',n:'Haldyn Glass'},
    {t:'HALEOSLABS.NS',n:'Haleos Labs'},
    {t:'HAPPSTMNDS.NS',n:'Happiest Minds Technologies'},
    {t:'HAPPYFORGE.NS',n:'Happy Forgings'},
    {t:'HARDWYN.NS',n:'Hardwyn India'},
    {t:'HARIOMPIPE.NS',n:'Hariom Pipe Industries'},
    {t:'HARRMALAYA.NS',n:'Harrisons  Malayalam'},
    {t:'HARSHA.NS',n:'Harsha Engineers International'},
    {t:'HATHWAY.NS',n:'Hathway Cable & Datacom'},
    {t:'HATSUN.NS',n:'Hatsun'},
    {t:'HAVELLS.NS',n:'Havells'},
    {t:'HAVISHA.NS',n:'Sri Havisha Hospitality And Infrastructure'},
    {t:'HAWKINCOOK.NS',n:'Hawkins Cookers'},
    {t:'HBESD.NS',n:'Hb Estate Developers'},
    {t:'HBLENGINE.NS',n:'Hbl Engineering'},
    {t:'HCC.NS',n:'Hindustan Construction Company'},
    {t:'HCG.NS',n:'Healthcare Global Enterprises'},
    {t:'HCL-INSYS.NS',n:'Hcl Infosystems'},
    {t:'HCLTECH.NS',n:'Hcl'},
    {t:'HDBFS.NS',n:'Hdb Financial Services'},
    {t:'HDFCAMC.NS',n:'Hdfc Amc'},
    {t:'HDFCBANK.NS',n:'Hdfc'},
    {t:'HDFCLIFE.NS',n:'Hdfc Life'},
    {t:'HEADSUP.NS',n:'Heads Up Ventures'},
    {t:'HEALTHX.NS',n:'Health X Platform'},
    {t:'HECPROJECT.NS',n:'Hec Infra Projects'},
    {t:'HEG.NS',n:'Heg'},
    {t:'HEIDELBERG.NS',n:'Heidelbergcement India'},
    {t:'HEMIPROP.NS',n:'Hemisphere Properties India'},
    {t:'HERANBA.NS',n:'Heranba Industries'},
    {t:'HERITGFOOD.NS',n:'Heritage Foods'},
    {t:'HEROMOTOCO.NS',n:'Hero'},
    {t:'HESTERBIO.NS',n:'Hester Biosciences'},
    {t:'HEXATRADEX.NS',n:'Hexa Tradex'},
    {t:'HEXT.NS',n:'Hexaware Technologies'},
    {t:'HFCL.NS',n:'Hfcl'},
    {t:'HGINFRA.NS',n:'H.G. Infra Engineering'},
    {t:'HGM.NS',n:'Handson Global Management (Hgm)'},
    {t:'HGS.NS',n:'Hinduja Global Solutions'},
    {t:'HIKAL.NS',n:'Hikal'},
    {t:'HIMATSEIDE.NS',n:'Himatsingka Seide'},
    {t:'HINDALCO.NS',n:'Hindalco'},
    {t:'HINDCOMPOS.NS',n:'Hindustan Composites'},
    {t:'HINDCOPPER.NS',n:'Hindustan Copper'},
    {t:'HINDOILEXP.NS',n:'Hindustan Oil Exploration Company'},
    {t:'HINDPETRO.NS',n:'Hpcl'},
    {t:'HINDUNILVR.NS',n:'Hul'},
    {t:'HINDWAREAP.NS',n:'Hindware Home Innovation'},
    {t:'HINDZINC.NS',n:'Hindustan Zinc'},
    {t:'HIRECT.NS',n:'Hind Rectifiers'},
    {t:'HISARMETAL.NS',n:'Hisar Metal Industries'},
    {t:'HITECH.NS',n:'Hi-Tech Pipes'},
    {t:'HITECHCORP.NS',n:'Hitech Corporation'},
    {t:'HLEGLAS.NS',n:'Hle Glascoat'},
    {t:'HLVLTD.NS',n:'Hlv'},
    {t:'HMAAGRO.NS',n:'Hma Agro Industries'},
    {t:'HMVL.NS',n:'Hindustan Media Ventures'},
    {t:'HNDFDS.NS',n:'Hindustan Foods'},
    {t:'HOMEFIRST.NS',n:'Home First Finance Company India'},
    {t:'HONASA.NS',n:'Honasa'},
    {t:'HONAUT.NS',n:'Honeywell Automation India'},
    {t:'HONDAPOWER.NS',n:'Honda India Power Products'},
    {t:'HPAL.NS',n:'Hp Adhesives'},
    {t:'HPIL.NS',n:'Hindprakash Industries'},
    {t:'HPL.NS',n:'Hpl Electric & Power'},
    {t:'HSCL.NS',n:'Himadri Speciality Chemical'},
    {t:'HTMEDIA.NS',n:'Ht Media'},
    {t:'HUBTOWN.NS',n:'Hubtown'},
    {t:'HUDCO.NS',n:'Housing & Urban Development Corporation'},
    {t:'HUHTAMAKI.NS',n:'Huhtamaki India'},
    {t:'HYBRIDFIN.NS',n:'Hybrid Financial Services'},
    {t:'HYUNDAI.NS',n:'Hyundai Motor India'},
    {t:'ICDSLTD.NS',n:'Icds'},
    {t:'ICEMAKE.NS',n:'Ice Make Refrigeration'},
    {t:'ICICIAMC.NS',n:'Icici Prudential Asset Management Company'},
    {t:'ICICIBANK.NS',n:'Icici'},
    {t:'ICICIGI.NS',n:'Icici Lombard General Insurance Company'},
    {t:'ICICIPRULI.NS',n:'Icici Prudential Life Insurance Company'},
    {t:'ICIL.NS',n:'Indo Count Industries'},
    {t:'ICRA.NS',n:'Icra'},
    {t:'IDBI.NS',n:'Idbi'},
    {t:'IDEA.NS',n:'Vi'},
    {t:'IDFCFIRSTB.NS',n:'Idfc First Bank'},
    {t:'IEX.NS',n:'Indian Energy Exchange'},
    {t:'IFBIND.NS',n:'Ifb Industries'},
    {t:'IFCI.NS',n:'Ifci'},
    {t:'IFGLEXPOR.NS',n:'Ifgl Refractories'},
    {t:'IGARASHI.NS',n:'Igarashi Motors India'},
    {t:'IGCL.NS',n:'Indogulf Cropsciences'},
    {t:'IGIL.NS',n:'International Gemological Institute'},
    {t:'IGL.NS',n:'Indraprastha Gas'},
    {t:'IGPL.NS',n:'Ig Petrochemicals'},
    {t:'IIFL.NS',n:'Iifl Finance'},
    {t:'IIFLCAPS.NS',n:'Iifl Capital Services'},
    {t:'IITL.NS',n:'Industrial Investment Trust'},
    {t:'IKIO.NS',n:'Ikio Technologies'},
    {t:'IKS.NS',n:'Inventurus Knowledge Solutions'},
    {t:'IMAGICAA.NS',n:'Imagicaaworld Entertainment'},
    {t:'IMAGINE.NS',n:'Boat'},
    {t:'IMFA.NS',n:'Indian Metals & Ferro Alloys'},
    {t:'IMPAL.NS',n:'India Motor Parts And Accessories'},
    {t:'INA.NS',n:'Insolation Energy'},
    {t:'INCREDIBLE.NS',n:'Incredible Industries'},
    {t:'INDBANK.NS',n:'Indbank Merchant Banking Services'},
    {t:'INDGN.NS',n:'Indegene'},
    {t:'INDHOTEL.NS',n:'The Indian Hotels Company'},
    {t:'INDIACEM.NS',n:'The India Cements'},
    {t:'INDIAGLYCO.NS',n:'India Glycols'},
    {t:'INDIAMART.NS',n:'Indiamart Intermesh'},
    {t:'INDIANB.NS',n:'Indian Bank'},
    {t:'INDIANCARD.NS',n:'Indian Card Clothing Company'},
    {t:'INDIANHUME.NS',n:'Indian Hume Pipe Company'},
    {t:'INDIASHLTR.NS',n:'India Shelter Finance Corporation'},
    {t:'INDIGO.NS',n:'Indigo'},
    {t:'INDIGOPNTS.NS',n:'Indigo Paints'},
    {t:'INDIQUBE.NS',n:'Indiqube Spaces'},
    {t:'INDNIPPON.NS',n:'India Nippon Electricals'},
    {t:'INDOAMIN.NS',n:'Indo Amines'},
    {t:'INDOBORAX.NS',n:'Indo Borax & Chemicals'},
    {t:'INDOCO.NS',n:'Indoco Remedies'},
    {t:'INDOFARM.NS',n:'Indo Farm Equipment'},
    {t:'INDORAMA.NS',n:'Indo Rama Synthetics (India)'},
    {t:'INDOSTAR.NS',n:'Indostar Capital Finance'},
    {t:'INDOTHAI.NS',n:'Indo Thai Securities'},
    {t:'INDOUS.NS',n:'Indo Us Biotech'},
    {t:'INDPRUD.NS',n:'Industrial & Prudential Investment Company'},
    {t:'INDRAMEDCO.NS',n:'Indraprastha Medical Corporation'},
    {t:'INDSWFTLAB.NS',n:'Ind-Swift Laboratories'},
    {t:'INDTERRAIN.NS',n:'Indian Terrain Fashions'},
    {t:'INDUSINDBK.NS',n:'Indusind'},
    {t:'INDUSTOWER.NS',n:'Indus Towers'},
    {t:'INFOBEAN.NS',n:'Infobeans Technologies'},
    {t:'INFOMEDIA.NS',n:'Infomedia Press'},
    {t:'INFY.NS',n:'Infy'},
    {t:'INGERRAND.NS',n:'Ingersoll Rand (India)'},
    {t:'INNOVACAP.NS',n:'Innova Captab'},
    {t:'INNOVANA.NS',n:'Innovana Thinklabs'},
    {t:'INNOVISION.NS',n:'Innovision'},
    {t:'INOXGREEN.NS',n:'Inox Green Energy Services'},
    {t:'INOXINDIA.NS',n:'Inox India'},
    {t:'INOXWIND.NS',n:'Inox Wind'},
    {t:'INSECTICID.NS',n:'Insecticides (India)'},
    {t:'INSPIRISYS.NS',n:'Inspirisys Solutions'},
    {t:'INTELLECT.NS',n:'Intellect Design Arena'},
    {t:'INTENTECH.NS',n:'Intense Technologies'},
    {t:'INTERARCH.NS',n:'Interarch Building Solutions'},
    {t:'INTLCONV.NS',n:'International Conveyors'},
    {t:'INVENTURE.NS',n:'Inventure Growth & Securities'},
    {t:'INVPRECQ.NS',n:'Investment & Precision Castings'},
    {t:'IOB.NS',n:'Indian Overseas Bank'},
    {t:'IOC.NS',n:'Ioc'},
    {t:'IOLCP.NS',n:'Iol Chemicals And Pharmaceuticals'},
    {t:'IONEXCHANG.NS',n:'Ion Exchange (India)'},
    {t:'IPCALAB.NS',n:'Ipca'},
    {t:'IPL.NS',n:'India Pesticides'},
    {t:'IRB.NS',n:'Irb Infrastructure Developers'},
    {t:'IRCON.NS',n:'Ircon International'},
    {t:'IRCTC.NS',n:'Irctc'},
    {t:'IREDA.NS',n:'Indian Renewable Energy Development Agency'},
    {t:'IRFC.NS',n:'Irfc'},
    {t:'IRIS.NS',n:'Iris Regtech Solutions'},
    {t:'IRISDOREME.NS',n:'Iris Clothings'},
    {t:'IRMENERGY.NS',n:'Irm Energy'},
    {t:'ISFT.NS',n:'Intrasoft Technologies'},
    {t:'ISGEC.NS',n:'Isgec Heavy Engineering'},
    {t:'ISHANCH.NS',n:'Ishan Dyes And Chemicals'},
    {t:'ITC.NS',n:'Itc'},
    {t:'ITCHOTELS.NS',n:'Itc Hotels'},
    {t:'ITDC.NS',n:'India Tourism Development Corporation'},
    {t:'ITI.NS',n:'Iti'},
    {t:'IVALUE.NS',n:'Ivalue Infosolutions'},
    {t:'IVC.NS',n:'Il&Fs Investment Managers'},
    {t:'IVP.NS',n:'Ivp'},
    {t:'IWP.NS',n:'The Indian Wood Products Company'},
    {t:'IXIGO.NS',n:'Le Travenues Technology'},
    {t:'IZMO.NS',n:'Izmo'},
    {t:'J&KBANK.NS',n:'The Jammu & Kashmir Bank'},
    {t:'JAGRAN.NS',n:'Jagran Prakashan'},
    {t:'JAGSNPHARM.NS',n:'Jagsonpal Pharmaceuticals'},
    {t:'JAICORPLTD.NS',n:'Jai Corp'},
    {t:'JAINREC.NS',n:'Jain Resource Recycling'},
    {t:'JAIPURKURT.NS',n:'Nandani Creation'},
    {t:'JAMNAAUTO.NS',n:'Jamna Auto Industries'},
    {t:'JARO.NS',n:'Jaro Institute Of Technology Management And Research'},
    {t:'JASH.NS',n:'Jash Engineering'},
    {t:'JAYAGROGN.NS',n:'Jayant Agro Organics'},
    {t:'JAYBARMARU.NS',n:'Jay Bharat Maruti'},
    {t:'JAYKAY.NS',n:'Jaykay Enterprises'},
    {t:'JAYNECOIND.NS',n:'Jayaswal Neco Industries'},
    {t:'JAYSREETEA.NS',n:'Jayshree Tea & Industries'},
    {t:'JBCHEPHARM.NS',n:'Jb Chemicals & Pharmaceuticals'},
    {t:'JBMA.NS',n:'Jbm Auto'},
    {t:'JETFREIGHT.NS',n:'Jet Freight Logistics'},
    {t:'JGCHEM.NS',n:'J.G.Chemicals'},
    {t:'JHS.NS',n:'Jhs Svendgaard Laboratories'},
    {t:'JINDALPHOT.NS',n:'Jindal Photo'},
    {t:'JINDALPOLY.NS',n:'Jindal Poly Films'},
    {t:'JINDALSAW.NS',n:'Jindal Saw'},
    {t:'JINDALSTEL.NS',n:'Jindal'},
    {t:'JINDRILL.NS',n:'Jindal Drilling And Industries'},
    {t:'JINDWORLD.NS',n:'Jindal Worldwide'},
    {t:'JIOFIN.NS',n:'Jio Financial Services'},
    {t:'JISLDVREQS.NS',n:'Jain Irrigation Systems'},
    {t:'JISLJALEQS.NS',n:'Jain Irrigation Systems'},
    {t:'JKCEMENT.NS',n:'Jk Cement'},
    {t:'JKIL.NS',n:'J.Kumar Infraprojects'},
    {t:'JKLAKSHMI.NS',n:'Jk Lakshmi Cement'},
    {t:'JKPAPER.NS',n:'Jk Paper'},
    {t:'JKTYRE.NS',n:'Jk Tyre & Industries'},
    {t:'JLHL.NS',n:'Jupiter Life Line Hospitals'},
    {t:'JMA.NS',n:'Jullundur Motor Agency (Delhi)'},
    {t:'JMFINANCIL.NS',n:'Jm Financial'},
    {t:'JNKINDIA.NS',n:'Jnk India'},
    {t:'JOCIL.NS',n:'Jocil'},
    {t:'JPOLYINVST.NS',n:'Jindal Poly Investment And Finance Company'},
    {t:'JPPOWER.NS',n:'Jaiprakash Power Ventures'},
    {t:'JSFB.NS',n:'Jana Small Finance Bank'},
    {t:'JSL.NS',n:'Jindal Stainless'},
    {t:'JSLL.NS',n:'Jeena Sikho Lifecare'},
    {t:'JSWCEMENT.NS',n:'Jsw Cement'},
    {t:'JSWDULUX.NS',n:'Jsw Dulux'},
    {t:'JSWENERGY.NS',n:'Jsw Energy'},
    {t:'JSWHL.NS',n:'Jsw Holdings'},
    {t:'JSWINFRA.NS',n:'Jsw Infrastructure'},
    {t:'JSWSTEEL.NS',n:'Jsw'},
    {t:'JTEKTINDIA.NS',n:'Jtekt India'},
    {t:'JTLIND.NS',n:'Jtl Industries'},
    {t:'JUBLCPL.NS',n:'Jubilant Agri And Consumer Products'},
    {t:'JUBLFOOD.NS',n:'Jubilant Food'},
    {t:'JUBLINGREA.NS',n:'Jubilant Ingrevia'},
    {t:'JUBLPHARMA.NS',n:'Jubilant Pharmova'},
    {t:'JUNIPER.NS',n:'Juniper Hotels'},
    {t:'JUSTDIAL.NS',n:'Just Dial'},
    {t:'JWL.NS',n:'Jupiter Wagons'},
    {t:'JYOTHYLAB.NS',n:'Jyothy Labs'},
    {t:'JYOTICNC.NS',n:'Jyoti Cnc Automation'},
    {t:'JYOTISTRUC.NS',n:'Jyoti Structures'},
    {t:'KABRAEXTRU.NS',n:'Kabra Extrusion Technik'},
    {t:'KAJARIACER.NS',n:'Kajaria Ceramics'},
    {t:'KALAMANDIR.NS',n:'Sai Silks (Kalamandir)'},
    {t:'KALPATARU.NS',n:'Kalpataru'},
    {t:'KALYANIFRG.NS',n:'Kalyani Forge'},
    {t:'KALYANKJIL.NS',n:'Kalyan Jewellers India'},
    {t:'KAMAHOLD.NS',n:'Kama Holdings'},
    {t:'KAMATHOTEL.NS',n:'Kamat Hotels (I)'},
    {t:'KAMDHENU.NS',n:'Kamdhenu'},
    {t:'KAMOPAINTS.NS',n:'Kamdhenu Ventures'},
    {t:'KANANIIND.NS',n:'Kanani Industries'},
    {t:'KANPRPLA.NS',n:'Kanpur Plastipack'},
    {t:'KANSAINER.NS',n:'Kansai Nerolac Paints'},
    {t:'KAPSTON.NS',n:'Kapston Services'},
    {t:'KARMAENG.NS',n:'Karma Energy'},
    {t:'KARURVYSYA.NS',n:'Karur Vysya Bank'},
    {t:'KAUSHALYA.NS',n:'Kaushalya Infrastructure Development Corporation'},
    {t:'KAVDEFENCE.NS',n:'Kavveri Defence & Wireless Technologies'},
    {t:'KAYA.NS',n:'Kaya'},
    {t:'KAYNES.NS',n:'Kaynes Technology India'},
    {t:'KCP.NS',n:'Kcp'},
    {t:'KCPSUGIND.NS',n:'Kcp Sugar And Industries Corporation'},
    {t:'KDDL.NS',n:'Kddl'},
    {t:'KEC.NS',n:'Kec International'},
    {t:'KEEPLEARN.NS',n:'Dsj Keep Learning'},
    {t:'KEI.NS',n:'Kei Industries'},
    {t:'KELLTONTEC.NS',n:'Kellton Tech Solutions'},
    {t:'KENNAMET.NS',n:'Kennametal India'},
    {t:'KERNEX.NS',n:'Kernex Microsystems (India)'},
    {t:'KEYFINSERV.NS',n:'Keynote Financial Services'},
    {t:'KFINTECH.NS',n:'Kfin Technologies'},
    {t:'KHADIM.NS',n:'Khadim India'},
    {t:'KHANDSE.NS',n:'Khandwala Securities'},
    {t:'KICL.NS',n:'Kalyani Investment Company'},
    {t:'KILITCH.NS',n:'Kilitch Drugs (India)'},
    {t:'KIMS.NS',n:'Krishna Institute Of Medical Sciences'},
    {t:'KINGFA.NS',n:'Kingfa Science & Technology (India)'},
    {t:'KIOCL.NS',n:'Kiocl'},
    {t:'KIRANVYPAR.NS',n:'Kiran Vyapar'},
    {t:'KIRIINDUS.NS',n:'Kiri Industries'},
    {t:'KIRLFER.NS',n:'Kirloskar Ferrous Industries'},
    {t:'KIRLOSBROS.NS',n:'Kirloskar Brothers'},
    {t:'KIRLOSENG.NS',n:'Kirloskar Oil Engines'},
    {t:'KIRLOSIND.NS',n:'Kirloskar Industries'},
    {t:'KIRLPNU.NS',n:'Kirloskar Pneumatic Company'},
    {t:'KISSHT.NS',n:'Onemi Technology Solutions'},
    {t:'KITEX.NS',n:'Kitex Garments'},
    {t:'KKCL.NS',n:'Kewal Kiran Clothing'},
    {t:'KLBRENG-B.NS',n:'Kilburn Engineering'},
    {t:'KMEW.NS',n:'Knowledge Marine & Engineering Works'},
    {t:'KMSUGAR.NS',n:'K.M.Sugar Mills'},
    {t:'KNAGRI.NS',n:'Kn Agri Resources'},
    {t:'KNRCON.NS',n:'Knr Constructions'},
    {t:'KOHINOOR.NS',n:'Kohinoor Foods'},
    {t:'KOKUYOCMLN.NS',n:'Kokuyo Camlin'},
    {t:'KOLTEPATIL.NS',n:'Kolte - Patil Developers'},
    {t:'KOPRAN.NS',n:'Kopran'},
    {t:'KOTAKBANK.NS',n:'Kotak'},
    {t:'KOTARISUG.NS',n:'Kothari Sugars And Chemicals'},
    {t:'KOTHARIPET.NS',n:'Kothari Petrochemicals'},
    {t:'KOTHARIPRO.NS',n:'Kothari Products'},
    {t:'KOTIC.NS',n:'Kothari Industrial Corporation'},
    {t:'KOTYARK.NS',n:'Kotyark Industries'},
    {t:'KOVAI.NS',n:'Kovai Medical Center & Hospital'},
    {t:'KPEL.NS',n:'K.P. Energy'},
    {t:'KPIGREEN.NS',n:'Kpi Green Energy'},
    {t:'KPIL.NS',n:'Kalpataru Projects International'},
    {t:'KPITTECH.NS',n:'Kpit'},
    {t:'KPL.NS',n:'Kwality Pharmaceuticals'},
    {t:'KPRMILL.NS',n:'K.P.R. Mill'},
    {t:'KRBL.NS',n:'Krbl'},
    {t:'KREBSBIO.NS',n:'Krebs Biochemicals And Industries'},
    {t:'KRIDHANINF.NS',n:'Kridhan Infra'},
    {t:'KRISHANA.NS',n:'Krishana Phoschem'},
    {t:'KRISHIVAL.NS',n:'Krishival Foods'},
    {t:'KRISHNADEF.NS',n:'Krishna Defence And Allied Industries'},
    {t:'KRITIKA.NS',n:'Kritika Wires'},
    {t:'KRONOX.NS',n:'Kronox Lab Sciences'},
    {t:'KROSS.NS',n:'Kross'},
    {t:'KRSNAA.NS',n:'Krsnaa Diagnostics'},
    {t:'KRYSTAL.NS',n:'Krystal Integrated Services'},
    {t:'KSB.NS',n:'Ksb'},
    {t:'KSCL.NS',n:'Kaveri Seed Company'},
    {t:'KSHINTL.NS',n:'Ksh International'},
    {t:'KSL.NS',n:'Kalyani Steels'},
    {t:'KSOLVES.NS',n:'Ksolves India'},
    {t:'KTKBANK.NS',n:'The Karnataka Bank'},
    {t:'KUANTUM.NS',n:'Kuantum Papers'},
    {t:'KWIL.NS',n:'Kwality Wall\'S (India)'},
    {t:'LAGNAM.NS',n:'Lagnam Spintex'},
    {t:'LAHOTIOV.NS',n:'Lahoti Overseas'},
    {t:'LAL.NS',n:'Lorenzini Apparels'},
    {t:'LALPATHLAB.NS',n:'Dr. Lal Path Labs Ltd'},
    {t:'LAMBODHARA.NS',n:'Lambodhara Textiles'},
    {t:'LANCORHOL.NS',n:'Lancor Holdings'},
    {t:'LANDMARK.NS',n:'Landmark Cars'},
    {t:'LANDSMILL.NS',n:'Landsmill Green'},
    {t:'LAOPALA.NS',n:'La Opala Rg'},
    {t:'LASA.NS',n:'Lasa Supergenerics'},
    {t:'LATENTVIEW.NS',n:'Latent View Analytics'},
    {t:'LAURUSLABS.NS',n:'Laurus'},
    {t:'LAXMIDENTL.NS',n:'Laxmi Dental'},
    {t:'LEMERITE.NS',n:'Le Merite Exports'},
    {t:'LEMONTREE.NS',n:'Lemon Tree Hotels'},
    {t:'LENSKART.NS',n:'Lenskart Solutions'},
    {t:'LEXUS.NS',n:'Lexus Granito (India)'},
    {t:'LFIC.NS',n:'Lakshmi Finance & Industrial Corporation'},
    {t:'LGBBROSLTD.NS',n:'Lg Balakrishnan & Bros'},
    {t:'LGEINDIA.NS',n:'Lg Electronics India'},
    {t:'LGHL.NS',n:'Laxmi Goldorna House'},
    {t:'LIBAS.NS',n:'Libas Consumer Products'},
    {t:'LIBERTSHOE.NS',n:'Liberty Shoes'},
    {t:'LICHSGFIN.NS',n:'Lic Housing Finance'},
    {t:'LICI.NS',n:'Lic'},
    {t:'LINC.NS',n:'Linc'},
    {t:'LINCOLN.NS',n:'Lincoln Pharmaceuticals'},
    {t:'LINDEINDIA.NS',n:'Linde India'},
    {t:'LLOYDSENGG.NS',n:'Lloyds Engineering Works'},
    {t:'LLOYDSENT.NS',n:'Lloyds Enterprises'},
    {t:'LLOYDSME.NS',n:'Lloyds Metals And Energy'},
    {t:'LMW.NS',n:'Lmw'},
    {t:'LODHA.NS',n:'Macrotech'},
    {t:'LORDSCHLO.NS',n:'Lords Chloro Alkali'},
    {t:'LOTUSDEV.NS',n:'Sri Lotus Developers And Realty'},
    {t:'LOTUSEYE.NS',n:'Lotus Eye Hospital And Institute'},
    {t:'LOVABLE.NS',n:'Lovable Lingerie'},
    {t:'LPDC.NS',n:'Landmark Property Development Company'},
    {t:'LT.NS',n:'L And T'},
    {t:'LTF.NS',n:'L&T Finance'},
    {t:'LTFOODS.NS',n:'Lt Foods'},
    {t:'LTIM.NS',n:'Lti'},
    {t:'LTM.NS',n:'Ltm'},
    {t:'LTTS.NS',n:'L&T Technology Services'},
    {t:'LUMAXIND.NS',n:'Lumax Industries'},
    {t:'LUMAXTECH.NS',n:'Lumax Auto Technologies'},
    {t:'LUPIN.NS',n:'Lupin'},
    {t:'LUXIND.NS',n:'Lux Industries'},
    {t:'LXCHEM.NS',n:'Laxmi Organic Industries'},
    {t:'LYKALABS.NS',n:'Lyka Labs'},
    {t:'LYPSAGEMS.NS',n:'Lypsa Gems & Jewellery'},
    {t:'M&M.NS',n:'M&M'},
    {t:'M&MFIN.NS',n:'Mahindra & Mahindra Financial Services'},
    {t:'MAANALU.NS',n:'Maan Aluminium'},
    {t:'MACPOWER.NS',n:'Macpower Cnc Machines'},
    {t:'MADHAV.NS',n:'Madhav Marbles And Granites'},
    {t:'MADHAVIPL.NS',n:'Madhav Infra Projects'},
    {t:'MADHUCON.NS',n:'Madhucon Projects'},
    {t:'MADRASFERT.NS',n:'Madras Fertilizers'},
    {t:'MAFATIND.NS',n:'Mafatlal Industries'},
    {t:'MAGADSUGAR.NS',n:'Magadh Sugar & Energy'},
    {t:'MAGNUM.NS',n:'Magnum Ventures'},
    {t:'MAHABANK.NS',n:'Bank Of Maharashtra'},
    {t:'MAHAPEXLTD.NS',n:'Maha Rashtra Apex Corporation'},
    {t:'MAHEPC.NS',n:'Mahindra Epc Irrigation'},
    {t:'MAHESHWARI.NS',n:'Maheshwari Logistics'},
    {t:'MAHLIFE.NS',n:'Mahindra Lifespace Developers'},
    {t:'MAHLOG.NS',n:'Mahindra Logistics'},
    {t:'MAHSCOOTER.NS',n:'Maharashtra Scooters'},
    {t:'MAHSEAMLES.NS',n:'Maharashtra Seamless'},
    {t:'MAITHANALL.NS',n:'Maithan Alloys'},
    {t:'MAJESAUT.NS',n:'Majestic Auto'},
    {t:'MALLCOM.NS',n:'Mallcom (India)'},
    {t:'MALUPAPER.NS',n:'Malu Paper Mills'},
    {t:'MAMATA.NS',n:'Mamata Machinery'},
    {t:'MANAKALUCO.NS',n:'Manaksia Aluminium Company'},
    {t:'MANAKCOAT.NS',n:'Manaksia Coated Metals & Industries'},
    {t:'MANAKSIA.NS',n:'Manaksia'},
    {t:'MANALIPETC.NS',n:'Manali Petrochemicals'},
    {t:'MANAPPURAM.NS',n:'Manappuram'},
    {t:'MANBA.NS',n:'Manba Finance'},
    {t:'MANCREDIT.NS',n:'Mangal Credit And Fincorp'},
    {t:'MANGLMCEM.NS',n:'Mangalam Cement'},
    {t:'MANINDS.NS',n:'Man Industries (India)'},
    {t:'MANINFRA.NS',n:'Man Infraconstruction'},
    {t:'MANKIND.NS',n:'Mankind Pharma'},
    {t:'MANOMAY.NS',n:'Manomay Tex India'},
    {t:'MANORAMA.NS',n:'Manorama Industries'},
    {t:'MANUGRAPH.NS',n:'Manugraph India'},
    {t:'MANYAVAR.NS',n:'Vedant Fashions'},
    {t:'MAPMYINDIA.NS',n:'C.E. Info Systems'},
    {t:'MARATHON.NS',n:'Marathon Nextgen Realty'},
    {t:'MARICO.NS',n:'Marico'},
    {t:'MARINE.NS',n:'Marine Electricals (India)'},
    {t:'MARKOLINES.NS',n:'Markolines Pavement Technologies'},
    {t:'MARKSANS.NS',n:'Marksans Pharma'},
    {t:'MARSONS.NS',n:'Marsons'},
    {t:'MARUTI.NS',n:'Maruti'},
    {t:'MASFIN.NS',n:'Mas Financial Services'},
    {t:'MASTEK.NS',n:'Mastek'},
    {t:'MASTERTR.NS',n:'Master Trust'},
    {t:'MATRIMONY.NS',n:'Matrimony.Com'},
    {t:'MAXESTATES.NS',n:'Max Estates'},
    {t:'MAXHEALTH.NS',n:'Max Health'},
    {t:'MAXIND.NS',n:'Max India'},
    {t:'MAYURUNIQ.NS',n:'Mayur Uniquoters Ltd'},
    {t:'MAZDA.NS',n:'Mazda'},
    {t:'MAZDOCK.NS',n:'Mazagon Dock Shipbuilders'},
    {t:'MBAPL.NS',n:'Madhya Bharat Agro Products'},
    {t:'MBEL.NS',n:'M & B Engineering'},
    {t:'MBLINFRA.NS',n:'Mbl Infrastructure'},
    {t:'MCCHRLS-B.NS',n:'Mac Charles India'},
    {t:'MCLOUD.NS',n:'Magellanic Cloud'},
    {t:'MCX.NS',n:'Mcx'},
    {t:'MEDANTA.NS',n:'Global Health'},
    {t:'MEDIASSIST.NS',n:'Medi Assist Healthcare Services'},
    {t:'MEDICAMEQ.NS',n:'Medicamen Biotech'},
    {t:'MEDICO.NS',n:'Medico Remedies'},
    {t:'MEDPLUS.NS',n:'Medplus Health Services'},
    {t:'MEESHO.NS',n:'Meesho'},
    {t:'MEGASTAR.NS',n:'Megastar Foods'},
    {t:'MENNPIS.NS',n:'Menon Pistons'},
    {t:'MENONBE.NS',n:'Menon Bearings'},
    {t:'MERCANTILE.NS',n:'Mercantile Ventures'},
    {t:'METROBRAND.NS',n:'Metro Brands'},
    {t:'METROGLOBL.NS',n:'Metroglobal'},
    {t:'METROPOLIS.NS',n:'Metropolis Healthcare'},
    {t:'MFML.NS',n:'Mahalaxmi Fabric Mills'},
    {t:'MFSL.NS',n:'Max Financial Services'},
    {t:'MGEL.NS',n:'Mangalam Global Enterprise'},
    {t:'MGL.NS',n:'Mahanagar Gas'},
    {t:'MHLXMIRU.NS',n:'Mahalaxmi Rubtech'},
    {t:'MHRIL.NS',n:'Mahindra Holidays & Resorts India'},
    {t:'MICEL.NS',n:'Mic Electronics'},
    {t:'MIDHANI.NS',n:'Mishra Dhatu Nigam'},
    {t:'MIDWESTLTD.NS',n:'Midwest'},
    {t:'MINDACORP.NS',n:'Minda Corporation'},
    {t:'MINDTECK.NS',n:'Mindteck (India)'},
    {t:'MIRZAINT.NS',n:'Mirza International'},
    {t:'MITCON.NS',n:'Mitcon Consultancy & Engineering Services'},
    {t:'MITTAL.NS',n:'Mittal Life Style'},
    {t:'MKPL.NS',n:'M K Proteins'},
    {t:'MMFL.NS',n:'Mm Forgings'},
    {t:'MMP.NS',n:'Mmp Industries'},
    {t:'MMTC.NS',n:'Mmtc'},
    {t:'MOBIKWIK.NS',n:'One Mobikwik Systems'},
    {t:'MODINATUR.NS',n:'Modi Naturals'},
    {t:'MODIRUBBER.NS',n:'Modi Rubber'},
    {t:'MODIS.NS',n:'Modis Navnirman'},
    {t:'MODISONLTD.NS',n:'Modison'},
    {t:'MODTHREAD.NS',n:'Modern Threads (India)'},
    {t:'MOHITIND.NS',n:'Mohit Industries'},
    {t:'MOIL.NS',n:'Moil'},
    {t:'MOKSH.NS',n:'Moksh Ornaments'},
    {t:'MOL.NS',n:'Meghmani Organics'},
    {t:'MOLDTECH.NS',n:'Mold-Tek Technologies'},
    {t:'MOLDTKPAC.NS',n:'Mold-Tek Packaging'},
    {t:'MONARCH.NS',n:'Monarch Networth Capital'},
    {t:'MONEYBOXX.NS',n:'Moneyboxx Finance'},
    {t:'MONTECARLO.NS',n:'Monte Carlo Fashions'},
    {t:'MOREPENLAB.NS',n:'Morepen Laboratories'},
    {t:'MOSCHIP.NS',n:'Moschip Technologies'},
    {t:'MOTHERSON.NS',n:'Motherson'},
    {t:'MOTILALOFS.NS',n:'Motilal Oswal Financial Services'},
    {t:'MOTISONS.NS',n:'Motisons Jewellers'},
    {t:'MOTOGENFIN.NS',n:'The Motor & General Finance'},
    {t:'MPHASIS.NS',n:'Mphasis'},
    {t:'MPSLTD.NS',n:'Mps'},
    {t:'MRF.NS',n:'Mrf'},
    {t:'MRPL.NS',n:'Mangalore Refinery And Petrochemicals'},
    {t:'MSPL.NS',n:'Msp Steel & Power'},
    {t:'MSTCLTD.NS',n:'Mstc'},
    {t:'MSUMI.NS',n:'Motherson Sumi Wiring India'},
    {t:'MTARTECH.NS',n:'Mtar Technologies'},
    {t:'MTNL.NS',n:'Mahanagar Telephone Nigam'},
    {t:'MUFIN.NS',n:'Mufin Green Finance'},
    {t:'MUFTI.NS',n:'Credo Brands Marketing'},
    {t:'MUKANDLTD.NS',n:'Mukand'},
    {t:'MUKKA.NS',n:'Mukka Proteins'},
    {t:'MUKTAARTS.NS',n:'Mukta Arts'},
    {t:'MUNJALAU.NS',n:'Munjal Auto Industries'},
    {t:'MUNJALSHOW.NS',n:'Munjal Showa'},
    {t:'MURUDCERA.NS',n:'Murudeshwar Ceramics'},
    {t:'MUTHOOTCAP.NS',n:'Muthoot Capital Services'},
    {t:'MUTHOOTFIN.NS',n:'Muthoot'},
    {t:'MUTHOOTMF.NS',n:'Muthoot Microfin'},
    {t:'MVGJL.NS',n:'Manoj Vaibhav Gems N Jewellers'},
    {t:'MWL.NS',n:'Mangalam Worldwide'},
    {t:'NACLIND.NS',n:'Nacl Industries'},
    {t:'NAGREEKEXP.NS',n:'Nagreeka Exports'},
    {t:'NAHARCAP.NS',n:'Nahar Capital And Financial Services'},
    {t:'NAHARINDUS.NS',n:'Nahar Industrial Enterprises'},
    {t:'NAHARPOLY.NS',n:'Nahar Poly Films'},
    {t:'NAM-INDIA.NS',n:'Nippon'},
    {t:'NARMADA.NS',n:'Narmada Agrobase'},
    {t:'NATCAPSUQ.NS',n:'Natural Capsules'},
    {t:'NATCOPHARM.NS',n:'Natco Pharma'},
    {t:'NATHBIOGEN.NS',n:'Nath Bio-Genes (India)'},
    {t:'NATIONALUM.NS',n:'National Aluminium Company'},
    {t:'NATIONSTD.NS',n:'National Standard (India)'},
    {t:'NAUKRI.NS',n:'Info Edge (India)'},
    {t:'NAVA.NS',n:'Nava'},
    {t:'NAVINFLUOR.NS',n:'Navin Fluorine'},
    {t:'NAVKARCORP.NS',n:'Navkar Corporation'},
    {t:'NAVKARURB.NS',n:'Navkar Urbanstructure'},
    {t:'NAVNETEDUL.NS',n:'Navneet Education'},
    {t:'NAZARA.NS',n:'Nazara Technologies'},
    {t:'NBCC.NS',n:'Nbcc (India)'},
    {t:'NBIFIN.NS',n:'N. B. I. Industrial Finance Company'},
    {t:'NCC.NS',n:'Ncc'},
    {t:'NCLIND.NS',n:'Ncl Industries'},
    {t:'NDGL.NS',n:'Naga Dhunseri Group'},
    {t:'NDL.NS',n:'Nandan Denim'},
    {t:'NDLVENTURE.NS',n:'Ndl Ventures'},
    {t:'NDRAUTO.NS',n:'Ndr Auto Components'},
    {t:'NDTV.NS',n:'New Delhi Television'},
    {t:'NEAGI.NS',n:'Neelamalai Agro Industries'},
    {t:'NECCLTD.NS',n:'North Eastern Carrying Corporation'},
    {t:'NELCAST.NS',n:'Nelcast'},
    {t:'NELCO.NS',n:'Nelco'},
    {t:'NEOGEN.NS',n:'Neogen Chemicals'},
    {t:'NEPHROPLUS.NS',n:'Nephrocare Health Services'},
    {t:'NESCO.NS',n:'Nesco'},
    {t:'NESTLEIND.NS',n:'Nestle'},
    {t:'NETWEB.NS',n:'Netweb Technologies India'},
    {t:'NETWORK18.NS',n:'Network18 Media & Investments'},
    {t:'NEULANDLAB.NS',n:'Neuland Laboratories'},
    {t:'NEWGEN.NS',n:'Newgen Software Technologies'},
    {t:'NEXTMEDIA.NS',n:'Next Mediaworks'},
    {t:'NFL.NS',n:'National Fertilizers'},
    {t:'NGLFINE.NS',n:'Ngl Fine-Chem'},
    {t:'NH.NS',n:'Narayana Hrudayalaya Ltd'},
    {t:'NHPC.NS',n:'Nhpc'},
    {t:'NIACL.NS',n:'The New India Assurance Company'},
    {t:'NIBE.NS',n:'Nibe'},
    {t:'NIBL.NS',n:'Nrb Industrial Bearings'},
    {t:'NIITLTD.NS',n:'Niit'},
    {t:'NIITMTS.NS',n:'Niit Learning Systems'},
    {t:'NILAINFRA.NS',n:'Nila Infrastructures'},
    {t:'NILASPACES.NS',n:'Nila Spaces'},
    {t:'NILE.NS',n:'Nile'},
    {t:'NILKAMAL.NS',n:'Nilkamal'},
    {t:'NIMBSPROJ.NS',n:'Nimbus Projects'},
    {t:'NIPPOBATRY.NS',n:'Indo-National'},
    {t:'NIRAJISPAT.NS',n:'Niraj Ispat Industries'},
    {t:'NIRLON.NS',n:'Nirlon'},
    {t:'NITCO.NS',n:'Nitco'},
    {t:'NITINSPIN.NS',n:'Nitin Spinners'},
    {t:'NITIRAJ.NS',n:'Nitiraj Engineers'},
    {t:'NITTAGELA.NS',n:'Nitta Gelatin India'},
    {t:'NIVABUPA.NS',n:'Niva Bupa Health Insurance Company'},
    {t:'NKIND.NS',n:'Nk Industries'},
    {t:'NLCINDIA.NS',n:'Nlc India'},
    {t:'NMDC.NS',n:'Nmdc'},
    {t:'NOCIL.NS',n:'Nocil'},
    {t:'NOIDATOLL.NS',n:'Noida Toll Bridge Company'},
    {t:'NORBTEAEXP.NS',n:'Norben Tea & Exports'},
    {t:'NORTHARC.NS',n:'Northern Arc Capital'},
    {t:'NOVAAGRI.NS',n:'Nova Agritech'},
    {t:'NOVARTIND.NS',n:'Novartis India'},
    {t:'NPST.NS',n:'Network People Services Technologies'},
    {t:'NRAIL.NS',n:'N R Agarwal Industries'},
    {t:'NRBBEARING.NS',n:'Nrb Bearing'},
    {t:'NRL.NS',n:'Nupur Recyclers'},
    {t:'NSIL.NS',n:'Nalwa Sons Investments'},
    {t:'NSLNISP.NS',n:'Nmdc Steel'},
    {t:'NTPC.NS',n:'Ntpc'},
    {t:'NTPCGREEN.NS',n:'Ntpc Green Energy'},
    {t:'NUCLEUS.NS',n:'Nucleus Software Exports'},
    {t:'NURECA.NS',n:'Nureca'},
    {t:'NUVAMA.NS',n:'Nuvama Wealth Management'},
    {t:'NUVOCO.NS',n:'Nuvoco'},
    {t:'NYKAA.NS',n:'Nykaa'},
    {t:'OAL.NS',n:'Oriental Aromatics'},
    {t:'OBCL.NS',n:'Orissa Bengal Carrier'},
    {t:'OBEROIRLTY.NS',n:'Oberoi'},
    {t:'OCCLLTD.NS',n:'Occl'},
    {t:'ODIGMA.NS',n:'Odigma Consultancy Solutions'},
    {t:'OFSS.NS',n:'Oracle Financial Services Software'},
    {t:'OIL.NS',n:'Oil India'},
    {t:'OLAELEC.NS',n:'Ola'},
    {t:'OLECTRA.NS',n:'Olectra Greentech'},
    {t:'OMAXE.NS',n:'Omaxe'},
    {t:'OMFREIGHT.NS',n:'Om Freight Forwarders'},
    {t:'OMINFRAL.NS',n:'Om Infra'},
    {t:'OMNI.NS',n:'Omnitech Engineering'},
    {t:'OMPOWER.NS',n:'Om Power Transmission'},
    {t:'ONEPOINT.NS',n:'One Point One Solutions'},
    {t:'ONESOURCE.NS',n:'Onesource Specialty Pharma'},
    {t:'ONGC.NS',n:'Ongc'},
    {t:'ONMOBILE.NS',n:'One Mobi'},
    {t:'ONWARDTEC.NS',n:'Onward Technologies'},
    {t:'OPTIEMUS.NS',n:'Optiemus Infracom'},
    {t:'ORBTEXP.NS',n:'Orbit Exports'},
    {t:'ORCHASP.NS',n:'Orchasp'},
    {t:'ORCHPHARMA.NS',n:'Orchid Pharma'},
    {t:'ORICONENT.NS',n:'Oricon Enterprises'},
    {t:'ORIENTALTL.NS',n:'Oriental Trimex'},
    {t:'ORIENTBELL.NS',n:'Orient Bell'},
    {t:'ORIENTCEM.NS',n:'Orient Cement'},
    {t:'ORIENTCER.NS',n:'Orient Ceratech'},
    {t:'ORIENTELEC.NS',n:'Orient Electric'},
    {t:'ORIENTHOT.NS',n:'Oriental Hotels'},
    {t:'ORIENTLTD.NS',n:'Orient Press'},
    {t:'ORIENTPPR.NS',n:'Orient Paper & Industries'},
    {t:'ORIENTTECH.NS',n:'Orient Technologies'},
    {t:'ORISSAMINE.NS',n:'The Orissa Minerals Development Company'},
    {t:'ORKLAINDIA.NS',n:'Orkla India'},
    {t:'OSWALGREEN.NS',n:'Oswal Greentech'},
    {t:'OSWALPUMPS.NS',n:'Oswal Pumps'},
    {t:'OSWALSEEDS.NS',n:'Shreeoswal Seeds And Chemicals'},
    {t:'PACEDIGITK.NS',n:'Pace Digitek'},
    {t:'PAGEIND.NS',n:'Page Industries'},
    {t:'PAISALO.NS',n:'Paisalo Digital'},
    {t:'PAKKA.NS',n:'Pakka'},
    {t:'PALASHSECU.NS',n:'Palash Securities'},
    {t:'PANACEABIO.NS',n:'Panacea Biotec'},
    {t:'PANACHE.NS',n:'Panache Digilife'},
    {t:'PANAMAPET.NS',n:'Panama Petrochem'},
    {t:'PANSARI.NS',n:'Pansari Developers'},
    {t:'PAR.NS',n:'Par Drugs And Chemicals'},
    {t:'PARACABLES.NS',n:'Paramount Communications'},
    {t:'PARADEEP.NS',n:'Paradeep Phosphates'},
    {t:'PARAGMILK.NS',n:'Parag Milk Foods'},
    {t:'PARAS.NS',n:'Paras Defence And Space Technologies'},
    {t:'PARASPETRO.NS',n:'Paras Petrofils'},
    {t:'PARKHOSPS.NS',n:'Park Medi World'},
    {t:'PARKHOTELS.NS',n:'Apeejay Surrendra Park Hotels'},
    {t:'PASHUPATI.NS',n:'Pashupati Cotspin'},
    {t:'PASUPTAC.NS',n:'Pasupati Acrylon'},
    {t:'PATANJALI.NS',n:'Patanjali Foods'},
    {t:'PATELENG.NS',n:'Patel Engineering'},
    {t:'PATELRMART.NS',n:'Patel Retail'},
    {t:'PATINTLOG.NS',n:'Patel Integrated Logistics'},
    {t:'PAUSHAKLTD.NS',n:'Paushak'},
    {t:'PAYTM.NS',n:'One97'},
    {t:'PCBL.NS',n:'Pcbl Chemical'},
    {t:'PCJEWELLER.NS',n:'Pc Jeweller'},
    {t:'PDMJEPAPER.NS',n:'Pudumjee Paper Products'},
    {t:'PDSL.NS',n:'Pds'},
    {t:'PENIND.NS',n:'Pennar Industries'},
    {t:'PERSISTENT.NS',n:'Persistent'},
    {t:'PETRONET.NS',n:'Petronet Lng'},
    {t:'PFC.NS',n:'Power Finance Corporation'},
    {t:'PFIZER.NS',n:'Pfizer'},
    {t:'PFS.NS',n:'Ptc India Financial Services'},
    {t:'PGEL.NS',n:'Pg Electroplast'},
    {t:'PGHH.NS',n:'Procter & Gamble Hygiene And Health Care'},
    {t:'PGHL.NS',n:'Procter & Gamble Health'},
    {t:'PGIL.NS',n:'Pearl Global Industries'},
    {t:'PHOENIXLTD.NS',n:'The Phoenix Mills'},
    {t:'PICCADIL.NS',n:'Piccadily Agro Industries'},
    {t:'PIDILITIND.NS',n:'Pidilite'},
    {t:'PIGL.NS',n:'Power & Instrumentation (Gujarat)'},
    {t:'PIIND.NS',n:'Pi Industries'},
    {t:'PILANIINVS.NS',n:'Pilani Investment And Industries Corporation'},
    {t:'PINELABS.NS',n:'Pine Labs'},
    {t:'PIONEEREMB.NS',n:'Pioneer Embroideries'},
    {t:'PIONRINV.NS',n:'Pioneer Investcorp'},
    {t:'PIRAMALFIN.NS',n:'Piramal Finance'},
    {t:'PITTIENG.NS',n:'Pitti Engineering'},
    {t:'PIXTRANS.NS',n:'Pix Transmissions'},
    {t:'PKTEA.NS',n:'The Peria Karamalai Tea & Produce Company'},
    {t:'PLASTIBLEN.NS',n:'Plastiblends India'},
    {t:'PLATIND.NS',n:'Platinum Industries'},
    {t:'PML.NS',n:'Paul Merchants'},
    {t:'PNB.NS',n:'Pnb'},
    {t:'PNBGILTS.NS',n:'Pnb Gilts'},
    {t:'PNBHOUSING.NS',n:'Pnb Housing Finance'},
    {t:'PNC.NS',n:'Pritish Nandy Communications'},
    {t:'PNCINFRA.NS',n:'Pnc Infratech'},
    {t:'PNGJL.NS',n:'P N Gadgil Jewellers'},
    {t:'PNGSREVA.NS',n:'Pngs Reva Diamond Jewellery'},
    {t:'POCL.NS',n:'Pondy Oxides & Chemicals'},
    {t:'PODDARMENT.NS',n:'Poddar Pigments'},
    {t:'POKARNA.NS',n:'Pokarna'},
    {t:'POLICYBZR.NS',n:'Pb Fintech'},
    {t:'POLYCAB.NS',n:'Polycab'},
    {t:'POLYMED.NS',n:'Poly Medicure'},
    {t:'POLYPLEX.NS',n:'Polyplex Corporation'},
    {t:'PONNIERODE.NS',n:'Ponni Sugars (Erode)'},
    {t:'POONAWALLA.NS',n:'Poonawalla Fincorp'},
    {t:'POWERGRID.NS',n:'Powergrid'},
    {t:'POWERICA.NS',n:'Powerica'},
    {t:'POWERINDIA.NS',n:'Hitachi Energy India'},
    {t:'POWERMECH.NS',n:'Power Mech Projects'},
    {t:'PPAP.NS',n:'Ppap Automotive'},
    {t:'PPL.NS',n:'Prakash Pipes'},
    {t:'PPLPHARMA.NS',n:'Piramal Pharma'},
    {t:'PRABHA.NS',n:'Prabha Energy'},
    {t:'PRADPME.NS',n:'Pradeep Metals'},
    {t:'PRAENG.NS',n:'Prajay Engineers Syndicate'},
    {t:'PRAJIND.NS',n:'Praj Industries'},
    {t:'PRAKASH.NS',n:'Prakash Industries'},
    {t:'PRAKASHSTL.NS',n:'Prakash Steelage'},
    {t:'PRAVEG.NS',n:'Praveg'},
    {t:'PRECAM.NS',n:'Precision Camshafts'},
    {t:'PRECOT.NS',n:'Precot'},
    {t:'PRECWIRE.NS',n:'Precision Wires India'},
    {t:'PREMCO.NS',n:'Premco Global'},
    {t:'PREMEXPLN.NS',n:'Premier Explosives'},
    {t:'PREMIERENE.NS',n:'Premier Energies'},
    {t:'PRESTIGE.NS',n:'Prestige Estates Projects'},
    {t:'PRICOLLTD.NS',n:'Pricol'},
    {t:'PRIMESECU.NS',n:'Prime Securities'},
    {t:'PRIMO.NS',n:'Primo Chemicals'},
    {t:'PRINCEPIPE.NS',n:'Prince Pipes And Fittings'},
    {t:'PRITI.NS',n:'Priti International'},
    {t:'PRITIKAUTO.NS',n:'Pritika Auto Industries'},
    {t:'PRIVISCL.NS',n:'Privi Speciality Chemicals'},
    {t:'PROSTARM.NS',n:'Prostarm Info Systems'},
    {t:'PROTEAN.NS',n:'Protean Egov Technologies'},
    {t:'PROZONER.NS',n:'Prozone Realty'},
    {t:'PRSMJOHNSN.NS',n:'Prism Johnson'},
    {t:'PRUDENT.NS',n:'Prudent Corporate Advisory Services'},
    {t:'PRUDMOULI.NS',n:'Prudential Sugar Corporation'},
    {t:'PSB.NS',n:'Punjab & Sind Bank'},
    {t:'PSPPROJECT.NS',n:'Psp Projects'},
    {t:'PTC.NS',n:'Ptc India'},
    {t:'PTCIL.NS',n:'Ptc Industries'},
    {t:'PTL.NS',n:'Ptl Enterprises'},
    {t:'PUNJABCHEM.NS',n:'Punjab Chemicals & Crop Protection'},
    {t:'PURVA.NS',n:'Puravankara'},
    {t:'PVP.NS',n:'Pvp Ventures'},
    {t:'PVRINOX.NS',n:'Pvr Inox'},
    {t:'PVSL.NS',n:'Popular Vehicles And Services'},
    {t:'PWL.NS',n:'Physicswallah'},
    {t:'PYRAMID.NS',n:'Pyramid Technoplast'},
    {t:'QUADFUTURE.NS',n:'Quadrant Future Tek'},
    {t:'QUESS.NS',n:'Quess Corp'},
    {t:'QUICKHEAL.NS',n:'Quick Heal Technologies'},
    {t:'QUINT.NS',n:'Quint Digital'},
    {t:'RACLGEAR.NS',n:'Racl Geartech'},
    {t:'RADAAN.NS',n:'Radaan Mediaworks India'},
    {t:'RADHIKAJWE.NS',n:'Radhika Jeweltech'},
    {t:'RADIANTCMS.NS',n:'Radiant Cash Management Services'},
    {t:'RADICO.NS',n:'Radico Khaitan'},
    {t:'RADIOCITY.NS',n:'Music Broadcast'},
    {t:'RAILTEL.NS',n:'Railtel Corporation Of India'},
    {t:'RAIN.NS',n:'Rain Industries'},
    {t:'RAINBOW.NS',n:'Rainbow Childrens Medicare'},
    {t:'RAJMET.NS',n:'Rajnandini Metal'},
    {t:'RAJOOENG.NS',n:'Rajoo Engineers'},
    {t:'RAJPALAYAM.NS',n:'Rajapalayam Mills'},
    {t:'RAJRATAN.NS',n:'Rajratan Global Wire'},
    {t:'RAJSREESUG.NS',n:'Rajshree Sugars & Chemicals'},
    {t:'RAJTV.NS',n:'Raj Television Network'},
    {t:'RALLIS.NS',n:'Rallis India'},
    {t:'RAMANEWS.NS',n:'Shree Rama Newsprint'},
    {t:'RAMAPHO.NS',n:'Rama Phosphates'},
    {t:'RAMASTEEL.NS',n:'Rama Steel Tubes'},
    {t:'RAMCOCEM.NS',n:'Ramco Cement'},
    {t:'RAMCOIND.NS',n:'Ramco Industries'},
    {t:'RAMCOSYS.NS',n:'Ramco Systems'},
    {t:'RAMKY.NS',n:'Ramky Infrastructure'},
    {t:'RAMRAT.NS',n:'Ram Ratna Wires'},
    {t:'RANASUG.NS',n:'Rana Sugars'},
    {t:'RANEHOLDIN.NS',n:'Rane Holdings'},
    {t:'RATEGAIN.NS',n:'Rategain Travel Technologies'},
    {t:'RATNAMANI.NS',n:'Ratnamani Metals & Tubes'},
    {t:'RATNAVEER.NS',n:'Ratnaveer Precision Engineering'},
    {t:'RAYMOND.NS',n:'Raymond'},
    {t:'RAYMONDLSL.NS',n:'Raymond Lifestyle'},
    {t:'RAYMONDREL.NS',n:'Raymond Realty'},
    {t:'RBA.NS',n:'Restaurant Brands Asia'},
    {t:'RBLBANK.NS',n:'Rbl Bank'},
    {t:'RBZJEWEL.NS',n:'Rbz Jewellers'},
    {t:'RCF.NS',n:'Rashtriya Chemicals And Fertilizers'},
    {t:'RECLTD.NS',n:'Rec'},
    {t:'REDINGTON.NS',n:'Redington'},
    {t:'REDTAPE.NS',n:'Redtape'},
    {t:'REFEX.NS',n:'Refex Industries'},
    {t:'REGENCERAM.NS',n:'Regency Ceramics'},
    {t:'RELAXO.NS',n:'Relaxo'},
    {t:'RELCHEMQ.NS',n:'Reliance Chemotex Industries'},
    {t:'RELIABLE.NS',n:'Reliable Data Services'},
    {t:'RELIANCE.NS',n:'Ril'},
    {t:'RELIGARE.NS',n:'Religare Enterprises'},
    {t:'RELTD.NS',n:'Ravindra Energy'},
    {t:'REMSONSIND.NS',n:'Remsons Industries'},
    {t:'RENUKA.NS',n:'Shree Renuka Sugars'},
    {t:'REPCOHOME.NS',n:'Repco Home Finance'},
    {t:'REPL.NS',n:'Rudrabhishek Enterprises'},
    {t:'REPRO.NS',n:'Repro India'},
    {t:'RESPONIND.NS',n:'Responsive Industries'},
    {t:'RETAIL.NS',n:'Jhs Svendgaard Retail Ventures'},
    {t:'RGL.NS',n:'Renaissance Global'},
    {t:'RHETAN.NS',n:'Rhetan Tmt'},
    {t:'RHIM.NS',n:'Rhi Magnesita India'},
    {t:'RHL.NS',n:'Robust Hotels'},
    {t:'RICOAUTO.NS',n:'Rico Auto Industries'},
    {t:'RIIL.NS',n:'Reliance Industrial Infrastructure'},
    {t:'RISHABH.NS',n:'Rishabh Instruments'},
    {t:'RITCO.NS',n:'Ritco Logistics'},
    {t:'RITES.NS',n:'Rites'},
    {t:'RKDL.NS',n:'Ravi Kumar Distilleries'},
    {t:'RKEC.NS',n:'Rkec Projects'},
    {t:'RKFORGE.NS',n:'Ramkrishna Forgings'},
    {t:'RKSWAMY.NS',n:'R K Swamy'},
    {t:'RMDRIP.NS',n:'R M Drip And Sprinklers Systems'},
    {t:'RML.NS',n:'Rane (Madras)'},
    {t:'RNBDENIMS.NS',n:'R&B Denims'},
    {t:'ROHLTD.NS',n:'Royal Orchid Hotels'},
    {t:'ROLEXRINGS.NS',n:'Rolex Rings'},
    {t:'ROML.NS',n:'Raj Oil Mills'},
    {t:'ROSSARI.NS',n:'Rossari Biotech'},
    {t:'ROSSELLIND.NS',n:'Rossell India'},
    {t:'ROSSTECH.NS',n:'Rossell Techsys'},
    {t:'ROTO.NS',n:'Roto Pumps'},
    {t:'ROUTE.NS',n:'Route Mobile'},
    {t:'RPEL.NS',n:'Raghav Productivity Enhancers'},
    {t:'RPGLIFE.NS',n:'Rpg Life Sciences'},
    {t:'RPOWER.NS',n:'Reliance Power'},
    {t:'RPPINFRA.NS',n:'R.P.P. Infra Projects'},
    {t:'RPPL.NS',n:'Rajshree Polypack'},
    {t:'RPSGVENT.NS',n:'Rpsg Ventures'},
    {t:'RPTECH.NS',n:'Rashi Peripherals'},
    {t:'RRIL.NS',n:'Rril'},
    {t:'RRKABEL.NS',n:'R R Kabel'},
    {t:'RSDFIN.NS',n:'Rsd Finance'},
    {t:'RSL.NS',n:'Rajputana Stainless'},
    {t:'RSWM.NS',n:'Rswm'},
    {t:'RSYSTEMS.NS',n:'R Systems International'},
    {t:'RTNINDIA.NS',n:'Rattanindia Enterprises'},
    {t:'RTNPOWER.NS',n:'Rattanindia Power'},
    {t:'RUBFILA.NS',n:'Rubfila International'},
    {t:'RUBICON.NS',n:'Rubicon Research'},
    {t:'RUBYMILLS.NS',n:'The Ruby Mills'},
    {t:'RUCHINFRA.NS',n:'Ruchi Infrastructure'},
    {t:'RUCHIRA.NS',n:'Ruchira Papers'},
    {t:'RUPA.NS',n:'Rupa & Company'},
    {t:'RUSHIL.NS',n:'Rushil Decor'},
    {t:'RUSTOMJEE.NS',n:'Keystone Realtors'},
    {t:'RVHL.NS',n:'Ravinder Heights'},
    {t:'RVNL.NS',n:'Rail Vikas'},
    {t:'RVTH.NS',n:'Revathi Equipment India'},
    {t:'SAATVIKGL.NS',n:'Saatvik Green Energy'},
    {t:'SADBHIN.NS',n:'Sadbhav Infrastructure Project'},
    {t:'SAFARI.NS',n:'Safari Industries (India)'},
    {t:'SAGARDEEP.NS',n:'Sagardeep Alloys'},
    {t:'SAGCEM.NS',n:'Sagar Cements'},
    {t:'SAGILITY.NS',n:'Sagility'},
    {t:'SAHLIBHFI.NS',n:'Shalibhadra Finance'},
    {t:'SAHYADRI.NS',n:'Sahyadri Industries'},
    {t:'SAIL.NS',n:'Steel Authority Of India'},
    {t:'SAILIFE.NS',n:'Sai Life Sciences'},
    {t:'SAIPARENT.NS',n:'Sai Parenterals'},
    {t:'SAKAR.NS',n:'Sakar Healthcare'},
    {t:'SAKHTISUG.NS',n:'Sakthi Sugars'},
    {t:'SAKSOFT.NS',n:'Saksoft'},
    {t:'SALASAR.NS',n:'Salasar Techno Engineering'},
    {t:'SALONA.NS',n:'Salona Cotspin'},
    {t:'SALZERELEC.NS',n:'Salzer Electronics'},
    {t:'SAMBHAAV.NS',n:'Sambhaav Media'},
    {t:'SAMBHV.NS',n:'Sambhv Steel Tubes'},
    {t:'SAMHI.NS',n:'Samhi Hotels'},
    {t:'SAMMAANCAP.NS',n:'Sammaan Capital'},
    {t:'SAMPANN.NS',n:'Sampann Utpadan India'},
    {t:'SANATHAN.NS',n:'Sanathan Textiles'},
    {t:'SANDESH.NS',n:'The Sandesh'},
    {t:'SANDHAR.NS',n:'Sandhar Technologies'},
    {t:'SANDUMA.NS',n:'Sandur Manganese & Iron Ores'},
    {t:'SANGAMIND.NS',n:'Sangam (India)'},
    {t:'SANGHVIMOV.NS',n:'Sanghvi Movers'},
    {t:'SANOFI.NS',n:'Sanofi India'},
    {t:'SANOFICONR.NS',n:'Sanofi Consumer Healthcare India'},
    {t:'SANSERA.NS',n:'Sansera Engineering'},
    {t:'SANSTAR.NS',n:'Sanstar'},
    {t:'SAPPHIRE.NS',n:'Sapphire Foods India'},
    {t:'SAPPL.NS',n:'Shree Ajit Pulp & Paper'},
    {t:'SARDAEN.NS',n:'Sarda Energy & Minerals'},
    {t:'SAREGAMA.NS',n:'Saregama India'},
    {t:'SARLAPOLY.NS',n:'Sarla Performance Fibers'},
    {t:'SASKEN.NS',n:'Sasken Technologies'},
    {t:'SATIA.NS',n:'Satia Industries'},
    {t:'SATIN.NS',n:'Satin Creditcare Network'},
    {t:'SAURASHCEM.NS',n:'Saurashtra Cement'},
    {t:'SAYAJIHOTL.NS',n:'Sayaji Hotels'},
    {t:'SBC.NS',n:'Sbc Exports'},
    {t:'SBCL.NS',n:'Shivalik Bimetal Controls'},
    {t:'SBFC.NS',n:'Sbfc Finance'},
    {t:'SBGLP.NS',n:'Suratwwala Business Group'},
    {t:'SBICARD.NS',n:'Sbi Cards And Payment Services'},
    {t:'SBILIFE.NS',n:'Sbi Life'},
    {t:'SBIN.NS',n:'Sbi'},
    {t:'SCANSTL.NS',n:'Scan Steels'},
    {t:'SCHAEFFLER.NS',n:'Schaeffler India'},
    {t:'SCHAND.NS',n:'S Chand And Company'},
    {t:'SCHNEIDER.NS',n:'Schneider Electric Infrastructure'},
    {t:'SCI.NS',n:'Shipping Corporation Of India'},
    {t:'SCILAL.NS',n:'Shipping Corporation Of India Land And Assets'},
    {t:'SCODATUBES.NS',n:'Scoda Tubes'},
    {t:'SDBL.NS',n:'Som Distilleries & Breweries'},
    {t:'SEAMECLTD.NS',n:'Seamec'},
    {t:'SECMARK.NS',n:'Secmark Consultancy'},
    {t:'SECURKLOUD.NS',n:'Securekloud Technologies'},
    {t:'SEDEMAC.NS',n:'Sedemac Mechatronics'},
    {t:'SEIL.NS',n:'Shanti Educational Initiatives'},
    {t:'SELMC.NS',n:'Sel Manufacturing Company'},
    {t:'SENCO.NS',n:'Senco Gold'},
    {t:'SENORES.NS',n:'Senores Pharmaceuticals'},
    {t:'SEPC.NS',n:'Sepc'},
    {t:'SERVOTECH.NS',n:'Servotech Renewable Power System'},
    {t:'SESHAPAPER.NS',n:'Seshasayee Paper And Boards'},
    {t:'SETL.NS',n:'Standard Engineering Technology'},
    {t:'SFL.NS',n:'Sheela Foam'},
    {t:'SGFIN.NS',n:'Sg Finserve'},
    {t:'SGIL.NS',n:'Synergy Green Industries'},
    {t:'SGL.NS',n:'Stl Global'},
    {t:'SGMART.NS',n:'Sg Mart'},
    {t:'SHADOWFAX.NS',n:'Shadowfax Technologies'},
    {t:'SHAH.NS',n:'Shah Metacorp'},
    {t:'SHAHALLOYS.NS',n:'Shah Alloys'},
    {t:'SHAILY.NS',n:'Shaily Engineering Plastics'},
    {t:'SHAKTIPUMP.NS',n:'Shakti Pumps (India)'},
    {t:'SHALBY.NS',n:'Shalby'},
    {t:'SHALPAINTS.NS',n:'Shalimar Paints'},
    {t:'SHANTI.NS',n:'Shanti Overseas (India)'},
    {t:'SHANTIGEAR.NS',n:'Shanthi Gears'},
    {t:'SHANTIGOLD.NS',n:'Shanti Gold International'},
    {t:'SHARDACROP.NS',n:'Sharda Cropchem'},
    {t:'SHARDAMOTR.NS',n:'Sharda Motor Industries'},
    {t:'SHARDUL.NS',n:'Shardul Securities'},
    {t:'SHAREINDIA.NS',n:'Share India Securities'},
    {t:'SHBAJRG.NS',n:'Shri Bajrang Alliance'},
    {t:'SHEMAROO.NS',n:'Shemaroo Entertainment'},
    {t:'SHILCTECH.NS',n:'Shilchar Technologies'},
    {t:'SHILPAMED.NS',n:'Shilpa Medicare'},
    {t:'SHINDL.NS',n:'Sharat Industries'},
    {t:'SHIVALIK.NS',n:'Shivalik Rasayan'},
    {t:'SHIVATEX.NS',n:'Shiva Texyarn'},
    {t:'SHIVAUM.NS',n:'Shiv Aum Steels'},
    {t:'SHK.NS',n:'S H Kelkar And Company'},
    {t:'SHOPERSTOP.NS',n:'Shoppers Stop'},
    {t:'SHRADHA.NS',n:'Shradha Realty'},
    {t:'SHREDIGCEM.NS',n:'Shree Digvijay Cement Co.Ltd'},
    {t:'SHREECEM.NS',n:'Shree'},
    {t:'SHREEJISPG.NS',n:'Shreeji Shipping Global'},
    {t:'SHREEPUSHK.NS',n:'Shree Pushkar Chemicals & Fertilisers'},
    {t:'SHREERAMA.NS',n:'Shree Rama Multi-Tech'},
    {t:'SHREYANIND.NS',n:'Shreyans Industries'},
    {t:'SHRIKRISH.NS',n:'Shri Krishna Devcon'},
    {t:'SHRINGARMS.NS',n:'Shringar House Of Mangalsutra'},
    {t:'SHRIPISTON.NS',n:'Shriram Pistons & Rings'},
    {t:'SHRIRAMFIN.NS',n:'Shriram Finance'},
    {t:'SHRIRAMPPS.NS',n:'Shriram Properties'},
    {t:'SHYAMCENT.NS',n:'Shyam Century Ferrous'},
    {t:'SHYAMMETL.NS',n:'Shyam Metalics And Energy'},
    {t:'SICAGEN.NS',n:'Sicagen India'},
    {t:'SIEMENS.NS',n:'Siemens'},
    {t:'SIGIND.NS',n:'Signet Industries'},
    {t:'SIGMA.NS',n:'Sigma Solve'},
    {t:'SIGNATURE.NS',n:'Signatureglobal (India)'},
    {t:'SIGNPOST.NS',n:'Signpost India'},
    {t:'SIKA.NS',n:'Sika Interplant Systems'},
    {t:'SIKKO.NS',n:'Sikko Industries'},
    {t:'SIL.NS',n:'Standard Industries'},
    {t:'SILGO.NS',n:'Silgo Retail'},
    {t:'SILINV.NS',n:'Sil Investments'},
    {t:'SILLYMONKS.NS',n:'Silly Monks Entertainment'},
    {t:'SILVERTUC.NS',n:'Silver Touch Technologies'},
    {t:'SIMPLEXINF.NS',n:'Simplex Infrastructures'},
    {t:'SINCLAIR.NS',n:'Sinclairs Hotels'},
    {t:'SINDHUTRAD.NS',n:'Sindhu Trade Links'},
    {t:'SINGERIND.NS',n:'Singer India'},
    {t:'SINTERCOM.NS',n:'Sintercom India'},
    {t:'SIRCA.NS',n:'Sirca Paints India'},
    {t:'SIS.NS',n:'Sis'},
    {t:'SIYSIL.NS',n:'Siyaram Silk Mills'},
    {t:'SJS.NS',n:'S.J.S. Enterprises'},
    {t:'SJVN.NS',n:'Sjvn'},
    {t:'SKFINDIA.NS',n:'Skf India'},
    {t:'SKFINDUS.NS',n:'Skf India (Industrial)'},
    {t:'SKIPPER.NS',n:'Skipper'},
    {t:'SKMEGGPROD.NS',n:'Skm Egg Products Export (India)'},
    {t:'SKYGOLD.NS',n:'Sky Gold And Diamonds'},
    {t:'SMARTWORKS.NS',n:'Smartworks Coworking Spaces'},
    {t:'SMCGLOBAL.NS',n:'Smc Global Securities'},
    {t:'SMLMAH.NS',n:'Sml Mahindra'},
    {t:'SMLT.NS',n:'Sarthak Metals'},
    {t:'SMSPHARMA.NS',n:'Sms Pharmaceuticals'},
    {t:'SNOWMAN.NS',n:'Snowman Logistics'},
    {t:'SOBHA.NS',n:'Sobha'},
    {t:'SOLARA.NS',n:'Solara Active Pharma Sciences'},
    {t:'SOLARINDS.NS',n:'Solar Industries'},
    {t:'SOLARWORLD.NS',n:'Solarworld Energy Solutions'},
    {t:'SOLEX.NS',n:'Solex Energy'},
    {t:'SOMANYCERA.NS',n:'Somany Ceramics'},
    {t:'SOMATEX.NS',n:'Soma Textiles & Industries'},
    {t:'SOMICONVEY.NS',n:'Somi Conveyor Beltings'},
    {t:'SONACOMS.NS',n:'Sona Blw Precision Forgings'},
    {t:'SONAL.NS',n:'Sonal Mercantile'},
    {t:'SONAMLTD.NS',n:'Sonam'},
    {t:'SONATSOFTW.NS',n:'Sonata Software'},
    {t:'SOTL.NS',n:'Savita Oil Technologies'},
    {t:'SOUTHBANK.NS',n:'The South Indian Bank'},
    {t:'SOUTHWEST.NS',n:'South West Pinnacle Exploration'},
    {t:'SPAL.NS',n:'S. P. Apparels'},
    {t:'SPANDANA.NS',n:'Spandana Sphoorty Financial'},
    {t:'SPARC.NS',n:'Sun Pharma Advanced Research Company'},
    {t:'SPCENET.NS',n:'Spacenet Enterprises India'},
    {t:'SPECIALITY.NS',n:'Speciality Restaurants'},
    {t:'SPECTRUM.NS',n:'Spectrum Electrical Industries'},
    {t:'SPENCERS.NS',n:'Spencer\'S Retail'},
    {t:'SPIC.NS',n:'Southern Petrochemicals Industries Corporation'},
    {t:'SPICEJET.NS',n:'Spicejet'},
    {t:'SPLIL.NS',n:'Spl Industries'},
    {t:'SPLPETRO.NS',n:'Supreme Petrochem'},
    {t:'SPMLINFRA.NS',n:'Spml Infra'},
    {t:'SPORTKING.NS',n:'Sportking India'},
    {t:'SRD.NS',n:'Shankar Lal Rampal Dye-Chem'},
    {t:'SREEL.NS',n:'Sreeleathers'},
    {t:'SRF.NS',n:'Srf'},
    {t:'SRGHFL.NS',n:'Srg Housing Finance'},
    {t:'SRHHYPOLTD.NS',n:'Sree Rayalaseema Hi-Strength Hypo'},
    {t:'SRM.NS',n:'Srm Contractors'},
    {t:'SRTL.NS',n:'Shree Ram Twistex'},
    {t:'SSDL.NS',n:'Saraswati Saree Depot'},
    {t:'SSWL.NS',n:'Steel Strips Wheels'},
    {t:'STALLION.NS',n:'Stallion India Fluorochemicals'},
    {t:'STANLEY.NS',n:'Stanley Lifestyles'},
    {t:'STAR.NS',n:'Strides Pharma Science'},
    {t:'STARCEMENT.NS',n:'Star Cement'},
    {t:'STARHEALTH.NS',n:'Star Health And Allied Insurance Company'},
    {t:'STARPAPER.NS',n:'Star Paper Mills'},
    {t:'STARTECK.NS',n:'Starteck Finance'},
    {t:'STCINDIA.NS',n:'The State Trading Corporation Of India'},
    {t:'STEELCAS.NS',n:'Steelcast'},
    {t:'STEELCITY.NS',n:'Steel City Securities'},
    {t:'STEELXIND.NS',n:'Steel Exchange India'},
    {t:'STEL.NS',n:'Stel Holdings'},
    {t:'STERTOOLS.NS',n:'Sterling Tools'},
    {t:'STOVEKRAFT.NS',n:'Stove Kraft'},
    {t:'STUDDS.NS',n:'Studds Accessories'},
    {t:'STYL.NS',n:'Seshaasai Technologies'},
    {t:'STYLAMIND.NS',n:'Stylam Industries'},
    {t:'STYRENIX.NS',n:'Styrenix Performance Materials'},
    {t:'SUBROS.NS',n:'Subros'},
    {t:'SUDARCOLOR.NS',n:'Sudarshan Colorants India'},
    {t:'SUDARSCHEM.NS',n:'Sudarshan Chemical Industries'},
    {t:'SUDEEPPHRM.NS',n:'Sudeep Pharma'},
    {t:'SUKHJITS.NS',n:'Sukhjit Starch & Chemicals'},
    {t:'SULA.NS',n:'Sula Vineyards'},
    {t:'SUMEETINDS.NS',n:'Sumeet Industries'},
    {t:'SUMICHEM.NS',n:'Sumitomo Chemical India'},
    {t:'SUMMITSEC.NS',n:'Summit Securities'},
    {t:'SUNCLAY.NS',n:'Sundaram Clayton'},
    {t:'SUNDARAM.NS',n:'Sundaram Multi Pap'},
    {t:'SUNDARMFIN.NS',n:'Sundaram Finance'},
    {t:'SUNDRMBRAK.NS',n:'Sundaram Brake Linings'},
    {t:'SUNDRMFAST.NS',n:'Sundram Fasteners'},
    {t:'SUNDROP.NS',n:'Sundrop Brands'},
    {t:'SUNFLAG.NS',n:'Sunflag Iron And Steel Company'},
    {t:'SUNPHARMA.NS',n:'Sun Pharma'},
    {t:'SUNTECK.NS',n:'Sunteck Realty'},
    {t:'SUNTV.NS',n:'Sun Tv Network'},
    {t:'SUPERHOUSE.NS',n:'Superhouse'},
    {t:'SUPERSPIN.NS',n:'Super Spinning Mills'},
    {t:'SUPRAJIT.NS',n:'Suprajit Engineering'},
    {t:'SUPREME.NS',n:'Supreme Holdings & Hospitality (India)'},
    {t:'SUPREMEIND.NS',n:'Supreme Industries'},
    {t:'SUPREMEINF.NS',n:'Supreme Infrastructure India'},
    {t:'SUPRIYA.NS',n:'Supriya Lifescience'},
    {t:'SURAJEST.NS',n:'Suraj Estate Developers'},
    {t:'SURAJLTD.NS',n:'Suraj'},
    {t:'SURAKSHA.NS',n:'Suraksha Diagnostic'},
    {t:'SURANASOL.NS',n:'Surana Solar'},
    {t:'SURANAT&P.NS',n:'Surana Telecom And Power'},
    {t:'SURYALA.NS',n:'Suryalata Spinning Mills'},
    {t:'SURYALAXMI.NS',n:'Suryalakshmi Cotton Mills'},
    {t:'SURYAROSNI.NS',n:'Surya Roshni'},
    {t:'SURYODAY.NS',n:'Suryoday Small Finance Bank'},
    {t:'SUTLEJTEX.NS',n:'Sutlej Textiles And Industries'},
    {t:'SUVEN.NS',n:'Suven Life Sciences'},
    {t:'SUVIDHAA.NS',n:'Suvidhaa Infoserve'},
    {t:'SUYOG.NS',n:'Suyog Telematics'},
    {t:'SUZLON.NS',n:'Suzlon'},
    {t:'SVLL.NS',n:'Shree Vasu Logistics'},
    {t:'SWANCORP.NS',n:'Swan Corp'},
    {t:'SWARAJENG.NS',n:'Swaraj Engines'},
    {t:'SWELECTES.NS',n:'Swelect Energy Systems'},
    {t:'SWIGGY.NS',n:'Swiggy'},
    {t:'SWSOLAR.NS',n:'Sterling And Wilson Renewable Energy'},
    {t:'SYMPHONY.NS',n:'Symphony'},
    {t:'SYNCOMF.NS',n:'Syncom Formulations (India)'},
    {t:'SYNGENE.NS',n:'Syngene'},
    {t:'SYRMA.NS',n:'Syrma Sgs Technology'},
    {t:'SYSTMTXC.NS',n:'Systematix Corporate Services'},
    {t:'TAALTECH.NS',n:'Taal Tech'},
    {t:'TAINWALCHM.NS',n:'Tainwala Chemical And Plastic (I)'},
    {t:'TAJGVK.NS',n:'Taj Gvk Hotels & Resorts'},
    {t:'TALBROAUTO.NS',n:'Talbros Automotive Components'},
    {t:'TAMBOLIIN.NS',n:'Tamboli Industries'},
    {t:'TANLA.NS',n:'Tanla Platforms'},
    {t:'TARACHAND.NS',n:'Tara Chand Infralogistic Solutions'},
    {t:'TARAPUR.NS',n:'Tarapur Transformers'},
    {t:'TARC.NS',n:'Tarc'},
    {t:'TARIL.NS',n:'Transformers And Rectifiers (India)'},
    {t:'TARMAT.NS',n:'Tarmat'},
    {t:'TARSONS.NS',n:'Tarsons Products'},
    {t:'TASTYBITE.NS',n:'Tasty Bite Eatables'},
    {t:'TATACAP.NS',n:'Tata Capital'},
    {t:'TATACHEM.NS',n:'Tata Chemicals'},
    {t:'TATACOMM.NS',n:'Tata Communications'},
    {t:'TATACONSUM.NS',n:'Tata Consumer'},
    {t:'TATAELXSI.NS',n:'Tata Elxsi'},
    {t:'TATAINVEST.NS',n:'Tata Investment Corporation'},
    {t:'TATAPOWER.NS',n:'Tata Power'},
    {t:'TATASTEEL.NS',n:'Tata Steel'},
    {t:'TATATECH.NS',n:'Tata Tech'},
    {t:'TATVA.NS',n:'Tatva Chintan Pharma Chem'},
    {t:'TBOTEK.NS',n:'Tbo Tek'},
    {t:'TBZ.NS',n:'Tribhovandas Bhimji Zaveri'},
    {t:'TCC.NS',n:'Tcc Concept'},
    {t:'TCI.NS',n:'Transport Corporation Of India'},
    {t:'TCIEXP.NS',n:'Tci Express'},
    {t:'TCIFINANCE.NS',n:'Tci Finance'},
    {t:'TCPLPACK.NS',n:'Tcpl Packaging'},
    {t:'TCS.NS',n:'Tcs'},
    {t:'TDPOWERSYS.NS',n:'Td Power Systems'},
    {t:'TEAMGTY.NS',n:'Team India Guaranty'},
    {t:'TEAMLEASE.NS',n:'Teamlease Services'},
    {t:'TECHM.NS',n:'Tech Mahindra'},
    {t:'TECHNOE.NS',n:'Techno Electric & Engineering Company'},
    {t:'TECHNVISN.NS',n:'Technvision Ventures'},
    {t:'TECILCHEM.NS',n:'Tecil Chemicals And Hydro Power'},
    {t:'TEGA.NS',n:'Tega Industries'},
    {t:'TEJASNET.NS',n:'Tejas Network'},
    {t:'TEMBO.NS',n:'Tembo Global Industries'},
    {t:'TENNIND.NS',n:'Tenneco Clean Air India'},
    {t:'TERASOFT.NS',n:'Tera Software'},
    {t:'TEXINFRA.NS',n:'Texmaco Infrastructure & Holdings'},
    {t:'TEXMOPIPES.NS',n:'Texmo Pipes And Products'},
    {t:'TEXRAIL.NS',n:'Texmaco Rail & Engineering'},
    {t:'TFCILTD.NS',n:'Tourism Finance Corporation Of India'},
    {t:'TFL.NS',n:'Transwarranty Finance'},
    {t:'TGBHOTELS.NS',n:'Tgb Banquets And Hotels'},
    {t:'THACKER.NS',n:'Thacker & Company'},
    {t:'THAKDEV.NS',n:'Thakkers Developers'},
    {t:'THANGAMAYL.NS',n:'Thangamayil Jewellery'},
    {t:'THEINVEST.NS',n:'The Investment Trust Of India'},
    {t:'THEJO.NS',n:'Thejo Engineering'},
    {t:'THELEELA.NS',n:'Leela Palaces Hotels & Resorts'},
    {t:'THEMISMED.NS',n:'Themis Medicare'},
    {t:'THERMAX.NS',n:'Thermax'},
    {t:'THOMASCOOK.NS',n:'Thomas Cook  (India)'},
    {t:'THOMASCOTT.NS',n:'Thomas Scott (India)'},
    {t:'THYROCARE.NS',n:'Thyrocare Technologies'},
    {t:'TI.NS',n:'Tilaknagar Industries'},
    {t:'TICL.NS',n:'Twamev Construction And Infrastructure'},
    {t:'TIIL.NS',n:'Technocraft Industries (India)'},
    {t:'TIINDIA.NS',n:'Tube Investments Of India'},
    {t:'TIL.NS',n:'Til'},
    {t:'TIMETECHNO.NS',n:'Time Technoplast'},
    {t:'TIMEX.NS',n:'Timex Group India'},
    {t:'TIMKEN.NS',n:'Timken India'},
    {t:'TINNARUBR.NS',n:'Tinna Rubber And Infrastructure'},
    {t:'TIPSFILMS.NS',n:'Tips Films'},
    {t:'TIPSMUSIC.NS',n:'Tips Music'},
    {t:'TIRUMALCHM.NS',n:'Thirumalai Chemicals'},
    {t:'TITAGARH.NS',n:'Titagarh Rail Systems'},
    {t:'TITAN.NS',n:'Titan'},
    {t:'TMB.NS',n:'Tamilnad Mercantile Bank'},
    {t:'TMCV.NS',n:'Tata Motors'},
    {t:'TMPV.NS',n:'Tata Group'},
    {t:'TNPETRO.NS',n:'Tamilnadu Petroproducts'},
    {t:'TNPL.NS',n:'Tamil Nadu Newsprint & Papers'},
    {t:'TNTELE.NS',n:'Tamilnadu Telecommunication'},
    {t:'TOLINS.NS',n:'Tolins Tyres'},
    {t:'TORNTPHARM.NS',n:'Torrent'},
    {t:'TORNTPOWER.NS',n:'Torrent Power'},
    {t:'TOTAL.NS',n:'Total Transport Systems'},
    {t:'TOUCHWOOD.NS',n:'Touchwood Entertainment'},
    {t:'TPHQ.NS',n:'Teamo Productions Hq'},
    {t:'TPLPLASTEH.NS',n:'Tpl Plastech'},
    {t:'TRACXN.NS',n:'Tracxn Technologies'},
    {t:'TRANSPEK.NS',n:'Transpek Industry'},
    {t:'TRANSRAILL.NS',n:'Transrail Lighting'},
    {t:'TRANSWORLD.NS',n:'Transworld Shipping Lines'},
    {t:'TRAVELFOOD.NS',n:'Travel Food Services'},
    {t:'TREEHOUSE.NS',n:'Tree House Education & Accessories'},
    {t:'TREJHARA.NS',n:'Trejhara Solutions'},
    {t:'TREL.NS',n:'Transindia Real Estate'},
    {t:'TRENT.NS',n:'Trent'},
    {t:'TRF.NS',n:'Trf'},
    {t:'TRIDENT.NS',n:'Trident'},
    {t:'TRIGYN.NS',n:'Trigyn Technologies'},
    {t:'TRITURBINE.NS',n:'Triveni Turbine'},
    {t:'TRIVENI.NS',n:'Triveni Engineering & Industries'},
    {t:'TRU.NS',n:'Trucap Finance'},
    {t:'TRUALT.NS',n:'Trualt Bioenergy'},
    {t:'TSFINV.NS',n:'Tsf Investments'},
    {t:'TTKHLTCARE.NS',n:'Ttk Healthcare'},
    {t:'TTKPRESTIG.NS',n:'Ttk Prestige'},
    {t:'TTL.NS',n:'T T'},
    {t:'TTML.NS',n:'Tata Teleservices (Maharashtra)'},
    {t:'TVSELECT.NS',n:'Tvs Electronics'},
    {t:'TVSHLTD.NS',n:'Tvs Holdings'},
    {t:'TVSMOTOR.NS',n:'Tvs Motor Company'},
    {t:'TVSSCS.NS',n:'Tvs Supply Chain Solutions'},
    {t:'TVSSRICHAK.NS',n:'Tvs Srichakra'},
    {t:'TVTODAY.NS',n:'Tv Today Network'},
    {t:'TVVISION.NS',n:'Tv Vision'},
    {t:'UBL.NS',n:'United Breweries'},
    {t:'UCAL.NS',n:'Ucal'},
    {t:'UCOBANK.NS',n:'Uco Bank'},
    {t:'UDS.NS',n:'Updater Services'},
    {t:'UEL.NS',n:'Ujaas Energy'},
    {t:'UFBL.NS',n:'United Foodbrands'},
    {t:'UFLEX.NS',n:'Uflex'},
    {t:'UFO.NS',n:'Ufo Moviez India'},
    {t:'UGARSUGAR.NS',n:'The Ugar Sugar Works'},
    {t:'UGROCAP.NS',n:'Ugro Capital'},
    {t:'UJJIVANSFB.NS',n:'Ujjivan Small Finance Bank'},
    {t:'ULTRACEMCO.NS',n:'Ultratech'},
    {t:'ULTRAMAR.NS',n:'Ultramarine & Pigments'},
    {t:'UMAEXPORTS.NS',n:'Uma Exports'},
    {t:'UMIYA-MRO.NS',n:'Umiya Buildcon'},
    {t:'UNICHEMLAB.NS',n:'Unichem Laboratories'},
    {t:'UNIDT.NS',n:'United Drilling Tools'},
    {t:'UNIECOM.NS',n:'Unicommerce Esolutions'},
    {t:'UNIENTER.NS',n:'Uniphos Enterprises'},
    {t:'UNIMECH.NS',n:'Unimech Aerospace And Manufacturing'},
    {t:'UNIONBANK.NS',n:'Union Bank Of India'},
    {t:'UNIPARTS.NS',n:'Uniparts India'},
    {t:'UNITDSPR.NS',n:'United Spirits'},
    {t:'UNITECH.NS',n:'Unitech'},
    {t:'UNITEDPOLY.NS',n:'United Polyfab Gujarat'},
    {t:'UNITEDTEA.NS',n:'The United Nilgiri Tea Estates Company'},
    {t:'UNIVASTU.NS',n:'Univastu India'},
    {t:'UNIVCABLES.NS',n:'Universal Cables'},
    {t:'UNOMINDA.NS',n:'Uno Minda'},
    {t:'UPL.NS',n:'Upl'},
    {t:'URAVIDEF.NS',n:'Uravi Defence And Technology'},
    {t:'URBANCO.NS',n:'Urban Company'},
    {t:'URJA.NS',n:'Urja Global'},
    {t:'USHAMART.NS',n:'Usha Martin'},
    {t:'USK.NS',n:'Udayshivakumar Infra'},
    {t:'UTIAMC.NS',n:'Uti Asset Management Company'},
    {t:'UTKARSHBNK.NS',n:'Utkarsh Small Finance Bank'},
    {t:'UTLSOLAR.NS',n:'Fujiyama Power Systems'},
    {t:'UTTAMSUGAR.NS',n:'Uttam Sugar Mills'},
    {t:'UYFINCORP.NS',n:'U. Y. Fincorp'},
    {t:'V2RETAIL.NS',n:'V2 Retail'},
    {t:'VADILALIND.NS',n:'Vadilal Industries'},
    {t:'VAIBHAVGBL.NS',n:'Vaibhav Global'},
    {t:'VAKRANGEE.NS',n:'Vakrangee'},
    {t:'VALIANTORG.NS',n:'Valiant Organics'},
    {t:'VARDHACRLC.NS',n:'Vardhman Acrylics'},
    {t:'VARROC.NS',n:'Varroc Engineering'},
    {t:'VASWANI.NS',n:'Vaswani Industries'},
    {t:'VBL.NS',n:'Varun Beverages'},
    {t:'VCL.NS',n:'Vaxtex Cotfab'},
    {t:'VEDL.NS',n:'Vedanta'},
    {t:'VEEDOL.NS',n:'Veedol Corporation'},
    {t:'VELJAN.NS',n:'Veljan Denison'},
    {t:'VENKEYS.NS',n:'Venky\'S (India)'},
    {t:'VENTIVE.NS',n:'Ventive Hospitality'},
    {t:'VENUSPIPES.NS',n:'Venus Pipes & Tubes'},
    {t:'VENUSREM.NS',n:'Venus Remedies'},
    {t:'VERANDA.NS',n:'Veranda Learning Solutions'},
    {t:'VERTOZ.NS',n:'Vertoz'},
    {t:'VESUVIUS.NS',n:'Vesuvius India'},
    {t:'VETO.NS',n:'Veto Switchgears And Cables'},
    {t:'VGL.NS',n:'Varvee Global'},
    {t:'VGUARD.NS',n:'V-Guard Industries'},
    {t:'VHL.NS',n:'Vardhman Holdings'},
    {t:'VIDHIING.NS',n:'Vidhi Specialty Food Ingredients'},
    {t:'VIDYAWIRES.NS',n:'Vidya Wires'},
    {t:'VIJAYA.NS',n:'Vijaya Diagnostic Centre'},
    {t:'VIKASECO.NS',n:'Vikas Ecotech'},
    {t:'VIKASLIFE.NS',n:'Vikas Lifecare'},
    {t:'VIKRAMSOLR.NS',n:'Vikram Solar'},
    {t:'VIKRAN.NS',n:'Vikran Engineering'},
    {t:'VIMTALABS.NS',n:'Vimta Labs'},
    {t:'VINATIORGA.NS',n:'Vinati Organics'},
    {t:'VINCOFE.NS',n:'Vintage Coffee And Beverages'},
    {t:'VINDHYATEL.NS',n:'Vindhya Telelinks'},
    {t:'VINNY.NS',n:'Vinny Overseas'},
    {t:'VINYLINDIA.NS',n:'Vinyl Chemicals (India)'},
    {t:'VIPIND.NS',n:'Vip Industries'},
    {t:'VIPULLTD.NS',n:'Vipul'},
    {t:'VIRINCHI.NS',n:'Virinchi'},
    {t:'VISAKAIND.NS',n:'Visaka Industries'},
    {t:'VISHNU.NS',n:'Vishnu Chemicals'},
    {t:'VISHWARAJ.NS',n:'Vishwaraj Sugar Industries'},
    {t:'VIVIDHA.NS',n:'Visagar Polytex'},
    {t:'VIYASH.NS',n:'Viyash Scientific'},
    {t:'VLSFINANCE.NS',n:'Vls Finance'},
    {t:'VMART.NS',n:'V Mart'},
    {t:'VMM.NS',n:'Vishal Mega Mart'},
    {t:'VOLTAMP.NS',n:'Voltamp Transformers'},
    {t:'VOLTAS.NS',n:'Voltas'},
    {t:'VRAJ.NS',n:'Vraj Iron And Steel'},
    {t:'VRLLOG.NS',n:'Vrl Logistics'},
    {t:'VSSL.NS',n:'Vardhman Special Steels'},
    {t:'VSTIND.NS',n:'Vst Industries'},
    {t:'VSTL.NS',n:'Vibhor Steel Tubes'},
    {t:'VSTTILLERS.NS',n:'V.S.T Tillers Tractors'},
    {t:'VTL.NS',n:'Vardhman Textiles'},
    {t:'WAAREEENER.NS',n:'Waaree Energies'},
    {t:'WAAREERTL.NS',n:'Waaree Renewable Technologies'},
    {t:'WABAG.NS',n:'Va Tech Wabag'},
    {t:'WAKEFIT.NS',n:'Wakefit Innovations'},
    {t:'WALCHANNAG.NS',n:'Walchandnagar Industries'},
    {t:'WCIL.NS',n:'Western Carriers (India)'},
    {t:'WEALTH.NS',n:'Wealth First Portfolio Managers'},
    {t:'WEBELSOLAR.NS',n:'Websol Energy System'},
    {t:'WEIZMANIND.NS',n:'Weizmann'},
    {t:'WEL.NS',n:'Wonder Electricals'},
    {t:'WELCORP.NS',n:'Welspun Corp'},
    {t:'WELENT.NS',n:'Welspun Enterprises'},
    {t:'WELINV.NS',n:'Welspun Investments And Commercials'},
    {t:'WELSPLSOL.NS',n:'Welspun Specialty Solutions'},
    {t:'WELSPUNLIV.NS',n:'Welspun Living'},
    {t:'WENDT.NS',n:'Wendt (India)'},
    {t:'WESTLIFE.NS',n:'Westlife Foodworld'},
    {t:'WEWORK.NS',n:'Wework India Management'},
    {t:'WHEELS.NS',n:'Wheels India'},
    {t:'WHIRLPOOL.NS',n:'Whirlpool Of India'},
    {t:'WILLAMAGOR.NS',n:'Williamson Magor & Company'},
    {t:'WIMPLAST.NS',n:'Wim Plast'},
    {t:'WINDLAS.NS',n:'Windlas Biotech'},
    {t:'WINDMACHIN.NS',n:'Windsor Machines'},
    {t:'WIPL.NS',n:'The Western India Plywoods'},
    {t:'WIPRO.NS',n:'Wipro'},
    {t:'WOCKPHARMA.NS',n:'Wockhardt'},
    {t:'WONDERLA.NS',n:'Wonderla Holidays'},
    {t:'WORTHPERI.NS',n:'Worth Peripherals'},
    {t:'WPIL.NS',n:'Wpil'},
    {t:'WSI.NS',n:'W S Industries (I)'},
    {t:'WSTCSTPAPR.NS',n:'West Coast Paper Mills'},
    {t:'XCHANGING.NS',n:'Xchanging Solutions'},
    {t:'XELPMOC.NS',n:'Xelpmoc Design And Tech'},
    {t:'XPROINDIA.NS',n:'Xpro India'},
    {t:'XTGLOBAL.NS',n:'Xtglobal Infotech'},
    {t:'YASHO.NS',n:'Yasho Industries'},
    {t:'YATHARTH.NS',n:'Yatharth Hospital & Trauma Care Services'},
    {t:'YATRA.NS',n:'Yatra Online'},
    {t:'YESBANK.NS',n:'Yes Bank'},
    {t:'YUKEN.NS',n:'Yuken India'},
    {t:'ZAGGLE.NS',n:'Zaggle Prepaid Ocean Services'},
    {t:'ZEEL.NS',n:'Zee Entertainment Enterprises'},
    {t:'ZEELEARN.NS',n:'Zee Learn'},
    {t:'ZEEMEDIA.NS',n:'Zee Media Corporation'},
    {t:'ZENITHEXPO.NS',n:'Zenith Exports'},
    {t:'ZENITHSTL.NS',n:'Zenith Steel Pipes & Industries'},
    {t:'ZENSARTECH.NS',n:'Zensar Technologies'},
    {t:'ZENTEC.NS',n:'Zen Technologies'},
    {t:'ZFCVINDIA.NS',n:'Zf Commercial Vehicle Control Systems India'},
    {t:'ZFSTEERING.NS',n:'Zf Steering Gear (India)'},
    {t:'ZODIACLOTH.NS',n:'Zodiac Clothing Company'},
    {t:'ZOMATO.NS',n:'Zomato'},
    {t:'ZOTA.NS',n:'Zota Health Care'},
    {t:'ZSARACOM.NS',n:'Saraswati Commercial India'},
    {t:'ZUARI.NS',n:'Zuari Agro Chemicals'},
    {t:'ZUARIIND.NS',n:'Zuari Industries'},
    {t:'ZYDUSLIFE.NS',n:'Zydus Lifesciences'},
    {t:'ZYDUSWELL.NS',n:'Zydus Wellness'},
];
